apiVersion: v1
kind: Service
metadata:
  name: machinesaggregate-service
  namespace: api
  labels:
    app: machinesaggregate
spec:
  selector:
    app: machinesaggregate
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
