// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/request/local": {
            "post": {
                "description": "Create feeedback for local.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create feedback for local endpoint",
                "parameters": [
                    {
                        "description": "feedback creating params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/feedback.FeedbackLocal"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success create feedback",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "Wrong body",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Somethink went wrong",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPError"
                        }
                    }
                }
            }
        },
        "/request/partnership": {
            "post": {
                "description": "Create feeedback for partnership.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create feedback for partnership endpoint",
                "parameters": [
                    {
                        "description": "feedback creating params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/feedback.FeedbackPartnership"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success create feedback",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "Wrong body",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Somethink went wrong",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPError"
                        }
                    }
                }
            }
        },
        "/score/rental": {
            "post": {
                "description": "Create feeedback for rental.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create feedback for rental endpoint",
                "parameters": [
                    {
                        "description": "feedback creating params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/feedback.Feedback"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success create feedback",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "Wrong body",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Somethink went wrong",
                        "schema": {
                            "$ref": "#/definitions/response.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "feedback.Feedback": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "rent_id": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "feedback.FeedbackLocal": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "feedback.FeedbackPartnership": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "company_name": {
                    "type": "string"
                },
                "contact_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "phone_num": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "response.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "security": [
        {
            "Bearer": []
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Swagger Feedback Service Api",
	Description:      "This is an API for feedback service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
