apiVersion: v1
kind: Service
metadata:
  name: expirationnotification-service
  namespace: api
  labels:
    app: expirationnotification
spec:
  selector:
    app: expirationnotification
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
  type: ClusterIP
