apiVersion: v1
kind: Service
metadata:
  name: sessionhandler-service
  namespace: api
  labels:
    app: sessionhandler
spec:
  selector:
    app: sessionhandler
  ports:
    - protocol: TCP
      port: 8094
      targetPort: 8094
  type: ClusterIP
