# Конфиг для запуска в Docker Compose (postgres, redis, redpanda по именам сервисов)
env: "local"
http:
  port: "9000"
  host: "0.0.0.0"
db:
  db_name: "postgres"
  db_password: "postgres"
  db_host: "postgres"
  db_port: "5432"
  db_user: "postgres"
kafka:
  username: ""
  password: ""
  brokers:
    - "redpanda:9092"
  consumer:
    topic: "output"
    consumer_group: "status-group-id"
redis:
  host: "redis"
  port: "6379"
  ttl: 3000s
user:
  user_path: "https://api.roy9.ru/"
  uesr_method : "POST"
  timeout : 3s
