apiVersion: v1
kind: Service
metadata:
  name: feedbackservice
  namespace: api
  labels:
    app: feedbackservice
spec:
  selector:
    app: feedbackservice
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095
  type: ClusterIP
