// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.29.3
// source: docker.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DockerState_Status int32

const (
	DockerState_Ok        DockerState_Status = 0
	DockerState_Launching DockerState_Status = 1
	DockerState_Error     DockerState_Status = 2
)

// Enum value maps for DockerState_Status.
var (
	DockerState_Status_name = map[int32]string{
		0: "Ok",
		1: "Launching",
		2: "Error",
	}
	DockerState_Status_value = map[string]int32{
		"Ok":        0,
		"Launching": 1,
		"Error":     2,
	}
)

func (x DockerState_Status) Enum() *DockerState_Status {
	p := new(DockerState_Status)
	*p = x
	return p
}

func (x DockerState_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DockerState_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_docker_proto_enumTypes[0].Descriptor()
}

func (DockerState_Status) Type() protoreflect.EnumType {
	return &file_docker_proto_enumTypes[0]
}

func (x DockerState_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DockerState_Status.Descriptor instead.
func (DockerState_Status) EnumDescriptor() ([]byte, []int) {
	return file_docker_proto_rawDescGZIP(), []int{1, 0}
}

// Data for start container (used in change mode request)
type DockerConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientUserId string                      `protobuf:"bytes,1,opt,name=client_user_id,json=clientUserId,proto3" json:"client_user_id,omitempty"` // who will use container
	Container    *ContainerConfiguration     `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	Auth         *ContainerAuthConfiguration `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (x *DockerConfiguration) Reset() {
	*x = DockerConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DockerConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerConfiguration) ProtoMessage() {}

func (x *DockerConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_docker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerConfiguration.ProtoReflect.Descriptor instead.
func (*DockerConfiguration) Descriptor() ([]byte, []int) {
	return file_docker_proto_rawDescGZIP(), []int{0}
}

func (x *DockerConfiguration) GetClientUserId() string {
	if x != nil {
		return x.ClientUserId
	}
	return ""
}

func (x *DockerConfiguration) GetContainer() *ContainerConfiguration {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *DockerConfiguration) GetAuth() *ContainerAuthConfiguration {
	if x != nil {
		return x.Auth
	}
	return nil
}

type DockerState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// container.local_port is the template_port (of course if template image correctly configured)
	// container.local_port have some transformations:
	//
	//	container.local_port
	//
	// -> container.host_port (host port in hypeOS)
	// -> real_port (port after auth proxy (if auth enabled for this port))
	//
	//	real_port - container.host_port or auth.outPort (container.host_port (auth.inPort) -> auth.outPort)
	Container *ContainerState     `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	Auth      *ContainerAuthState `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	Status    DockerState_Status  `protobuf:"varint,3,opt,name=status,proto3,enum=runtime.DockerState_Status" json:"status,omitempty"`
	StatusMsg string              `protobuf:"bytes,4,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"` // Can be useful in error (also "Stopped") case
}

func (x *DockerState) Reset() {
	*x = DockerState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DockerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerState) ProtoMessage() {}

func (x *DockerState) ProtoReflect() protoreflect.Message {
	mi := &file_docker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerState.ProtoReflect.Descriptor instead.
func (*DockerState) Descriptor() ([]byte, []int) {
	return file_docker_proto_rawDescGZIP(), []int{1}
}

func (x *DockerState) GetContainer() *ContainerState {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *DockerState) GetAuth() *ContainerAuthState {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *DockerState) GetStatus() DockerState_Status {
	if x != nil {
		return x.Status
	}
	return DockerState_Ok
}

func (x *DockerState) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type DockerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Available bool   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Version   string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *DockerInfo) Reset() {
	*x = DockerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DockerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerInfo) ProtoMessage() {}

func (x *DockerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_docker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerInfo.ProtoReflect.Descriptor instead.
func (*DockerInfo) Descriptor() ([]byte, []int) {
	return file_docker_proto_rawDescGZIP(), []int{2}
}

func (x *DockerInfo) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *DockerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_docker_proto protoreflect.FileDescriptor

var file_docker_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x1a, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb3, 0x01, 0x0a, 0x13, 0x44, 0x6f, 0x63,
	0x6b, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x24, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x22, 0xf5,
	0x01, 0x0a, 0x0b, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x35,
	0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x73, 0x67, 0x22, 0x2a, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x10, 0x02, 0x22, 0x44, 0x0a, 0x0a, 0x44, 0x6f, 0x63, 0x6b, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x04, 0x5a, 0x02,
	0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_docker_proto_rawDescOnce sync.Once
	file_docker_proto_rawDescData = file_docker_proto_rawDesc
)

func file_docker_proto_rawDescGZIP() []byte {
	file_docker_proto_rawDescOnce.Do(func() {
		file_docker_proto_rawDescData = protoimpl.X.CompressGZIP(file_docker_proto_rawDescData)
	})
	return file_docker_proto_rawDescData
}

var file_docker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_docker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_docker_proto_goTypes = []interface{}{
	(DockerState_Status)(0),            // 0: runtime.DockerState.Status
	(*DockerConfiguration)(nil),        // 1: runtime.DockerConfiguration
	(*DockerState)(nil),                // 2: runtime.DockerState
	(*DockerInfo)(nil),                 // 3: runtime.DockerInfo
	(*ContainerConfiguration)(nil),     // 4: runtime.ContainerConfiguration
	(*ContainerAuthConfiguration)(nil), // 5: runtime.ContainerAuthConfiguration
	(*ContainerState)(nil),             // 6: runtime.ContainerState
	(*ContainerAuthState)(nil),         // 7: runtime.ContainerAuthState
}
var file_docker_proto_depIdxs = []int32{
	4, // 0: runtime.DockerConfiguration.container:type_name -> runtime.ContainerConfiguration
	5, // 1: runtime.DockerConfiguration.auth:type_name -> runtime.ContainerAuthConfiguration
	6, // 2: runtime.DockerState.container:type_name -> runtime.ContainerState
	7, // 3: runtime.DockerState.auth:type_name -> runtime.ContainerAuthState
	0, // 4: runtime.DockerState.status:type_name -> runtime.DockerState.Status
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_docker_proto_init() }
func file_docker_proto_init() {
	if File_docker_proto != nil {
		return
	}
	file_container_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_docker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DockerConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DockerState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DockerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_docker_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_docker_proto_goTypes,
		DependencyIndexes: file_docker_proto_depIdxs,
		EnumInfos:         file_docker_proto_enumTypes,
		MessageInfos:      file_docker_proto_msgTypes,
	}.Build()
	File_docker_proto = out.File
	file_docker_proto_rawDesc = nil
	file_docker_proto_goTypes = nil
	file_docker_proto_depIdxs = nil
}
