// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.28.3
// source: template.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PortProtocol int32

const (
	PortProtocol_HTTP PortProtocol = 0
	PortProtocol_TCP  PortProtocol = 1
	PortProtocol_UDP  PortProtocol = 2
)

// Enum value maps for PortProtocol.
var (
	PortProtocol_name = map[int32]string{
		0: "HTTP",
		1: "TCP",
		2: "UDP",
	}
	PortProtocol_value = map[string]int32{
		"HTTP": 0,
		"TCP":  1,
		"UDP":  2,
	}
)

func (x PortProtocol) Enum() *PortProtocol {
	p := new(PortProtocol)
	*p = x
	return p
}

func (x PortProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PortProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_template_proto_enumTypes[0].Descriptor()
}

func (PortProtocol) Type() protoreflect.EnumType {
	return &file_template_proto_enumTypes[0]
}

func (x PortProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PortProtocol.Descriptor instead.
func (PortProtocol) EnumDescriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{0}
}

type StatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatReq) Reset() {
	*x = StatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatReq) ProtoMessage() {}

func (x *StatReq) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatReq.ProtoReflect.Descriptor instead.
func (*StatReq) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{0}
}

type StatResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// по неизвестной причине (вычислено опытным путём) для того чтобы получить тоже значение
	// что и при docker system df (там вывод в MB) нужно делить на 1000
	TotalImgMem float32 `protobuf:"fixed32,1,opt,name=total_img_mem,json=totalImgMem,proto3" json:"total_img_mem,omitempty"` // [KB]
}

func (x *StatResp) Reset() {
	*x = StatResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResp) ProtoMessage() {}

func (x *StatResp) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResp.ProtoReflect.Descriptor instead.
func (*StatResp) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{1}
}

func (x *StatResp) GetTotalImgMem() float32 {
	if x != nil {
		return x.TotalImgMem
	}
	return 0
}

type GetTemplateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// filter by available types ["local", "compute", "runtime", "base"]
	// P.S. Вроде как пока кроме "local" ничего нет, так что ["local"] скорее всего сработает как Get All
	Types []string `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
}

func (x *GetTemplateReq) Reset() {
	*x = GetTemplateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTemplateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateReq) ProtoMessage() {}

func (x *GetTemplateReq) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateReq.ProtoReflect.Descriptor instead.
func (*GetTemplateReq) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{2}
}

func (x *GetTemplateReq) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

type GetTemplateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Templates []*GetTemplateResp_TemplateInfo `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
}

func (x *GetTemplateResp) Reset() {
	*x = GetTemplateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTemplateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateResp) ProtoMessage() {}

func (x *GetTemplateResp) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateResp.ProtoReflect.Descriptor instead.
func (*GetTemplateResp) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{3}
}

func (x *GetTemplateResp) GetTemplates() []*GetTemplateResp_TemplateInfo {
	if x != nil {
		return x.Templates
	}
	return nil
}

type DownloadTemplateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Template *TemplateData                     `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Download *DownloadTemplateReq_DownloadInfo `protobuf:"bytes,2,opt,name=download,proto3" json:"download,omitempty"`
}

func (x *DownloadTemplateReq) Reset() {
	*x = DownloadTemplateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadTemplateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTemplateReq) ProtoMessage() {}

func (x *DownloadTemplateReq) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTemplateReq.ProtoReflect.Descriptor instead.
func (*DownloadTemplateReq) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadTemplateReq) GetTemplate() *TemplateData {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *DownloadTemplateReq) GetDownload() *DownloadTemplateReq_DownloadInfo {
	if x != nil {
		return x.Download
	}
	return nil
}

type DownloadTemplateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DownloadTemplateResp) Reset() {
	*x = DownloadTemplateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadTemplateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTemplateResp) ProtoMessage() {}

func (x *DownloadTemplateResp) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTemplateResp.ProtoReflect.Descriptor instead.
func (*DownloadTemplateResp) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{5}
}

type DownloadTemplateStreamResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	General *DownloadTemplateStreamResp_Progress   `protobuf:"bytes,1,opt,name=general,proto3" json:"general,omitempty"`
	Layers  []*DownloadTemplateStreamResp_Progress `protobuf:"bytes,2,rep,name=layers,proto3" json:"layers,omitempty"`
	Err     *string                                `protobuf:"bytes,3,opt,name=err,proto3,oneof" json:"err,omitempty"`
}

func (x *DownloadTemplateStreamResp) Reset() {
	*x = DownloadTemplateStreamResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadTemplateStreamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTemplateStreamResp) ProtoMessage() {}

func (x *DownloadTemplateStreamResp) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTemplateStreamResp.ProtoReflect.Descriptor instead.
func (*DownloadTemplateStreamResp) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadTemplateStreamResp) GetGeneral() *DownloadTemplateStreamResp_Progress {
	if x != nil {
		return x.General
	}
	return nil
}

func (x *DownloadTemplateStreamResp) GetLayers() []*DownloadTemplateStreamResp_Progress {
	if x != nil {
		return x.Layers
	}
	return nil
}

func (x *DownloadTemplateStreamResp) GetErr() string {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return ""
}

type RemoveTemplateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateID string `protobuf:"bytes,1,opt,name=templateID,proto3" json:"templateID,omitempty"`
}

func (x *RemoveTemplateReq) Reset() {
	*x = RemoveTemplateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTemplateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTemplateReq) ProtoMessage() {}

func (x *RemoveTemplateReq) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTemplateReq.ProtoReflect.Descriptor instead.
func (*RemoveTemplateReq) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveTemplateReq) GetTemplateID() string {
	if x != nil {
		return x.TemplateID
	}
	return ""
}

type RemoveTemplateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveTemplateResp) Reset() {
	*x = RemoveTemplateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTemplateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTemplateResp) ProtoMessage() {}

func (x *RemoveTemplateResp) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTemplateResp.ProtoReflect.Descriptor instead.
func (*RemoveTemplateResp) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{8}
}

type CleanCacheReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateID string `protobuf:"bytes,1,opt,name=templateID,proto3" json:"templateID,omitempty"`
	// volumes that used by other users (in merchant modes)
	CleanHostUsageCache bool `protobuf:"varint,2,opt,name=clean_host_usage_cache,json=cleanHostUsageCache,proto3" json:"clean_host_usage_cache,omitempty"`
	// volumes that used by this computer user
	CleanLocalUsageCache bool `protobuf:"varint,3,opt,name=clean_local_usage_cache,json=cleanLocalUsageCache,proto3" json:"clean_local_usage_cache,omitempty"`
}

func (x *CleanCacheReq) Reset() {
	*x = CleanCacheReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CleanCacheReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanCacheReq) ProtoMessage() {}

func (x *CleanCacheReq) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanCacheReq.ProtoReflect.Descriptor instead.
func (*CleanCacheReq) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{9}
}

func (x *CleanCacheReq) GetTemplateID() string {
	if x != nil {
		return x.TemplateID
	}
	return ""
}

func (x *CleanCacheReq) GetCleanHostUsageCache() bool {
	if x != nil {
		return x.CleanHostUsageCache
	}
	return false
}

func (x *CleanCacheReq) GetCleanLocalUsageCache() bool {
	if x != nil {
		return x.CleanLocalUsageCache
	}
	return false
}

type CleanCacheResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CleanCacheResp) Reset() {
	*x = CleanCacheResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CleanCacheResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanCacheResp) ProtoMessage() {}

func (x *CleanCacheResp) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanCacheResp.ProtoReflect.Descriptor instead.
func (*CleanCacheResp) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{10}
}

type TemplateData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type    string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// template configuration
	Configuration *TemplateData_Configuration `protobuf:"bytes,4,opt,name=configuration,proto3" json:"configuration,omitempty"`
	Data          string                      `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"` // for debug
}

func (x *TemplateData) Reset() {
	*x = TemplateData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateData) ProtoMessage() {}

func (x *TemplateData) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateData.ProtoReflect.Descriptor instead.
func (*TemplateData) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{11}
}

func (x *TemplateData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TemplateData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TemplateData) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TemplateData) GetConfiguration() *TemplateData_Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *TemplateData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type TemplatePort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// port is port from container (used as portID)
	Port string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	// title is name for this port usage
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// In this version, only HTTP ports supports authentication and proxy (Host_Proxy_VM)
	Protocol PortProtocol `protobuf:"varint,4,opt,name=protocol,proto3,enum=runtime.PortProtocol" json:"protocol,omitempty"`
	// auth flag is used to know if port supports authentication
	// authentication will be used if [auth = true] in change mode request
	// P.S. if basic user of this server, this information is not important (use state stream)
	AuthAvailable bool `protobuf:"varint,5,opt,name=auth_available,json=authAvailable,proto3" json:"auth_available,omitempty"`
}

func (x *TemplatePort) Reset() {
	*x = TemplatePort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplatePort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplatePort) ProtoMessage() {}

func (x *TemplatePort) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplatePort.ProtoReflect.Descriptor instead.
func (*TemplatePort) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{12}
}

func (x *TemplatePort) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *TemplatePort) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TemplatePort) GetProtocol() PortProtocol {
	if x != nil {
		return x.Protocol
	}
	return PortProtocol_HTTP
}

func (x *TemplatePort) GetAuthAvailable() bool {
	if x != nil {
		return x.AuthAvailable
	}
	return false
}

type GetTemplateResp_TemplateInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Template   *TemplateData                            `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	ImageUsage float32                                  `protobuf:"fixed32,2,opt,name=image_usage,json=imageUsage,proto3" json:"image_usage,omitempty"` // [KB]
	LocalUsage *GetTemplateResp_TemplateInfo_LocalUsage `protobuf:"bytes,3,opt,name=local_usage,json=localUsage,proto3" json:"local_usage,omitempty"`
	RentUsage  *GetTemplateResp_TemplateInfo_RentUsage  `protobuf:"bytes,4,opt,name=rent_usage,json=rentUsage,proto3" json:"rent_usage,omitempty"`
}

func (x *GetTemplateResp_TemplateInfo) Reset() {
	*x = GetTemplateResp_TemplateInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTemplateResp_TemplateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateResp_TemplateInfo) ProtoMessage() {}

func (x *GetTemplateResp_TemplateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateResp_TemplateInfo.ProtoReflect.Descriptor instead.
func (*GetTemplateResp_TemplateInfo) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetTemplateResp_TemplateInfo) GetTemplate() *TemplateData {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *GetTemplateResp_TemplateInfo) GetImageUsage() float32 {
	if x != nil {
		return x.ImageUsage
	}
	return 0
}

func (x *GetTemplateResp_TemplateInfo) GetLocalUsage() *GetTemplateResp_TemplateInfo_LocalUsage {
	if x != nil {
		return x.LocalUsage
	}
	return nil
}

func (x *GetTemplateResp_TemplateInfo) GetRentUsage() *GetTemplateResp_TemplateInfo_RentUsage {
	if x != nil {
		return x.RentUsage
	}
	return nil
}

// Info about local usage (im mode "Local")
type GetTemplateResp_TemplateInfo_LocalUsage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemUsage float32 `protobuf:"fixed32,2,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"` // [KB]
}

func (x *GetTemplateResp_TemplateInfo_LocalUsage) Reset() {
	*x = GetTemplateResp_TemplateInfo_LocalUsage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTemplateResp_TemplateInfo_LocalUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateResp_TemplateInfo_LocalUsage) ProtoMessage() {}

func (x *GetTemplateResp_TemplateInfo_LocalUsage) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateResp_TemplateInfo_LocalUsage.ProtoReflect.Descriptor instead.
func (*GetTemplateResp_TemplateInfo_LocalUsage) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *GetTemplateResp_TemplateInfo_LocalUsage) GetMemUsage() float32 {
	if x != nil {
		return x.MemUsage
	}
	return 0
}

// Info about rent usage (im merchant modes)
type GetTemplateResp_TemplateInfo_RentUsage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemUsage float32 `protobuf:"fixed32,2,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"` // [KB]
}

func (x *GetTemplateResp_TemplateInfo_RentUsage) Reset() {
	*x = GetTemplateResp_TemplateInfo_RentUsage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTemplateResp_TemplateInfo_RentUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateResp_TemplateInfo_RentUsage) ProtoMessage() {}

func (x *GetTemplateResp_TemplateInfo_RentUsage) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateResp_TemplateInfo_RentUsage.ProtoReflect.Descriptor instead.
func (*GetTemplateResp_TemplateInfo_RentUsage) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{3, 0, 1}
}

func (x *GetTemplateResp_TemplateInfo_RentUsage) GetMemUsage() float32 {
	if x != nil {
		return x.MemUsage
	}
	return 0
}

type DownloadTemplateReq_DownloadInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName string `protobuf:"bytes,4,opt,name=imageName,proto3" json:"imageName,omitempty"`
	ImageTag  string `protobuf:"bytes,5,opt,name=imageTag,proto3" json:"imageTag,omitempty"`
}

func (x *DownloadTemplateReq_DownloadInfo) Reset() {
	*x = DownloadTemplateReq_DownloadInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadTemplateReq_DownloadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTemplateReq_DownloadInfo) ProtoMessage() {}

func (x *DownloadTemplateReq_DownloadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTemplateReq_DownloadInfo.ProtoReflect.Descriptor instead.
func (*DownloadTemplateReq_DownloadInfo) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{4, 0}
}

func (x *DownloadTemplateReq_DownloadInfo) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *DownloadTemplateReq_DownloadInfo) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

type DownloadTemplateStreamResp_Progress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Current float32 `protobuf:"fixed32,1,opt,name=current,proto3" json:"current,omitempty"` // [KB]
	Total   float32 `protobuf:"fixed32,2,opt,name=total,proto3" json:"total,omitempty"`     // [KB]
	Percent float32 `protobuf:"fixed32,3,opt,name=percent,proto3" json:"percent,omitempty"` // [%]
}

func (x *DownloadTemplateStreamResp_Progress) Reset() {
	*x = DownloadTemplateStreamResp_Progress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadTemplateStreamResp_Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTemplateStreamResp_Progress) ProtoMessage() {}

func (x *DownloadTemplateStreamResp_Progress) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTemplateStreamResp_Progress.ProtoReflect.Descriptor instead.
func (*DownloadTemplateStreamResp_Progress) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{6, 0}
}

func (x *DownloadTemplateStreamResp_Progress) GetCurrent() float32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *DownloadTemplateStreamResp_Progress) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DownloadTemplateStreamResp_Progress) GetPercent() float32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type TemplateData_Configuration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UseGPU bool            `protobuf:"varint,1,opt,name=useGPU,proto3" json:"useGPU,omitempty"`
	Ports  []*TemplatePort `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	// template volumes paths
	Volumes []string `protobuf:"bytes,4,rep,name=volumes,proto3" json:"volumes,omitempty"`
	// strings format in envs must be: ["param", "param = value", ...]
	Envs []string `protobuf:"bytes,3,rep,name=envs,proto3" json:"envs,omitempty"`
}

func (x *TemplateData_Configuration) Reset() {
	*x = TemplateData_Configuration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_template_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateData_Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateData_Configuration) ProtoMessage() {}

func (x *TemplateData_Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_template_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateData_Configuration.ProtoReflect.Descriptor instead.
func (*TemplateData_Configuration) Descriptor() ([]byte, []int) {
	return file_template_proto_rawDescGZIP(), []int{11, 0}
}

func (x *TemplateData_Configuration) GetUseGPU() bool {
	if x != nil {
		return x.UseGPU
	}
	return false
}

func (x *TemplateData_Configuration) GetPorts() []*TemplatePort {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *TemplateData_Configuration) GetVolumes() []string {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *TemplateData_Configuration) GetEnvs() []string {
	if x != nil {
		return x.Envs
	}
	return nil
}

var File_template_proto protoreflect.FileDescriptor

var file_template_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x09, 0x0a, 0x07, 0x53, 0x74, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x22, 0x2e, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x22, 0x0a, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x69, 0x6d, 0x67, 0x5f, 0x6d, 0x65,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x6d,
	0x67, 0x4d, 0x65, 0x6d, 0x22, 0x26, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0xb7, 0x03, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x43, 0x0a, 0x09, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x73, 0x1a, 0xde, 0x02, 0x0a, 0x0c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x31, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x52, 0x0a, 0x0b, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x31, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x75, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x4f,
	0x0a, 0x0a, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x30, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x65, 0x6e, 0x74, 0x5f, 0x75,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x09, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x61, 0x67, 0x65, 0x1a,
	0x2a, 0x0a, 0x0b, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x55, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x29, 0x0a, 0x0a, 0x52,
	0x65, 0x6e, 0x74, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6d,
	0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6d, 0x65,
	0x6d, 0x55, 0x73, 0x61, 0x67, 0x65, 0x22, 0xd9, 0x01, 0x0a, 0x13, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x31,
	0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x12, 0x45, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x48, 0x0a, 0x0c, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x54,
	0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x54,
	0x61, 0x67, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x9f, 0x02, 0x0a, 0x1a, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x46, 0x0a, 0x07, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x2e,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x6c, 0x12, 0x44, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2c, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x06, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x15, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x65, 0x72, 0x72, 0x88, 0x01, 0x01, 0x1a, 0x54,
	0x0a, 0x08, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65,
	0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x70, 0x65, 0x72,
	0x63, 0x65, 0x6e, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x65, 0x72, 0x72, 0x22, 0x33, 0x0a, 0x11,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49,
	0x44, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x9b, 0x01, 0x0a, 0x0d, 0x43, 0x6c, 0x65, 0x61,
	0x6e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x44, 0x12, 0x33, 0x0a, 0x16, 0x63, 0x6c, 0x65,
	0x61, 0x6e, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x63, 0x6c, 0x65, 0x61, 0x6e,
	0x48, 0x6f, 0x73, 0x74, 0x55, 0x73, 0x61, 0x67, 0x65, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x35,
	0x0a, 0x17, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x75, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x14, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x55, 0x73, 0x61, 0x67, 0x65,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0xb0, 0x02, 0x0a, 0x0c, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x49, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x82, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x47, 0x50,
	0x55, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x73, 0x65, 0x47, 0x50, 0x55, 0x12,
	0x2b, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x6e, 0x76, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x65, 0x6e, 0x76, 0x73, 0x22, 0x92, 0x01, 0x0a, 0x0c, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x75, 0x74, 0x68,
	0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x2a,
	0x2a, 0x0a, 0x0c, 0x50, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12,
	0x08, 0x0a, 0x04, 0x48, 0x54, 0x54, 0x50, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x43, 0x50,
	0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x44, 0x50, 0x10, 0x02, 0x32, 0xa2, 0x03, 0x0a, 0x08,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x12, 0x10, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x03, 0x47, 0x65,
	0x74, 0x12, 0x17, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x08, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x1c, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x44, 0x6f, 0x77,
	0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x1d, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c,
	0x6f, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x57, 0x0a, 0x0e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x12, 0x1c, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x44, 0x6f,
	0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x23, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x30, 0x01, 0x12, 0x43, 0x0a, 0x06, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x12, 0x1a, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x1b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x3f, 0x0a, 0x0a, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x16, 0x2e,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x43, 0x6c, 0x65, 0x61, 0x6e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_template_proto_rawDescOnce sync.Once
	file_template_proto_rawDescData = file_template_proto_rawDesc
)

func file_template_proto_rawDescGZIP() []byte {
	file_template_proto_rawDescOnce.Do(func() {
		file_template_proto_rawDescData = protoimpl.X.CompressGZIP(file_template_proto_rawDescData)
	})
	return file_template_proto_rawDescData
}

var file_template_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_template_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_template_proto_goTypes = []interface{}{
	(PortProtocol)(0),                               // 0: runtime.PortProtocol
	(*StatReq)(nil),                                 // 1: runtime.StatReq
	(*StatResp)(nil),                                // 2: runtime.StatResp
	(*GetTemplateReq)(nil),                          // 3: runtime.GetTemplateReq
	(*GetTemplateResp)(nil),                         // 4: runtime.GetTemplateResp
	(*DownloadTemplateReq)(nil),                     // 5: runtime.DownloadTemplateReq
	(*DownloadTemplateResp)(nil),                    // 6: runtime.DownloadTemplateResp
	(*DownloadTemplateStreamResp)(nil),              // 7: runtime.DownloadTemplateStreamResp
	(*RemoveTemplateReq)(nil),                       // 8: runtime.RemoveTemplateReq
	(*RemoveTemplateResp)(nil),                      // 9: runtime.RemoveTemplateResp
	(*CleanCacheReq)(nil),                           // 10: runtime.CleanCacheReq
	(*CleanCacheResp)(nil),                          // 11: runtime.CleanCacheResp
	(*TemplateData)(nil),                            // 12: runtime.TemplateData
	(*TemplatePort)(nil),                            // 13: runtime.TemplatePort
	(*GetTemplateResp_TemplateInfo)(nil),            // 14: runtime.GetTemplateResp.TemplateInfo
	(*GetTemplateResp_TemplateInfo_LocalUsage)(nil), // 15: runtime.GetTemplateResp.TemplateInfo.Local_usage
	(*GetTemplateResp_TemplateInfo_RentUsage)(nil),  // 16: runtime.GetTemplateResp.TemplateInfo.Rent_usage
	(*DownloadTemplateReq_DownloadInfo)(nil),        // 17: runtime.DownloadTemplateReq.DownloadInfo
	(*DownloadTemplateStreamResp_Progress)(nil),     // 18: runtime.DownloadTemplateStreamResp.Progress
	(*TemplateData_Configuration)(nil),              // 19: runtime.TemplateData.Configuration
}
var file_template_proto_depIdxs = []int32{
	14, // 0: runtime.GetTemplateResp.templates:type_name -> runtime.GetTemplateResp.TemplateInfo
	12, // 1: runtime.DownloadTemplateReq.template:type_name -> runtime.TemplateData
	17, // 2: runtime.DownloadTemplateReq.download:type_name -> runtime.DownloadTemplateReq.DownloadInfo
	18, // 3: runtime.DownloadTemplateStreamResp.general:type_name -> runtime.DownloadTemplateStreamResp.Progress
	18, // 4: runtime.DownloadTemplateStreamResp.layers:type_name -> runtime.DownloadTemplateStreamResp.Progress
	19, // 5: runtime.TemplateData.configuration:type_name -> runtime.TemplateData.Configuration
	0,  // 6: runtime.TemplatePort.protocol:type_name -> runtime.PortProtocol
	12, // 7: runtime.GetTemplateResp.TemplateInfo.template:type_name -> runtime.TemplateData
	15, // 8: runtime.GetTemplateResp.TemplateInfo.local_usage:type_name -> runtime.GetTemplateResp.TemplateInfo.Local_usage
	16, // 9: runtime.GetTemplateResp.TemplateInfo.rent_usage:type_name -> runtime.GetTemplateResp.TemplateInfo.Rent_usage
	13, // 10: runtime.TemplateData.Configuration.ports:type_name -> runtime.TemplatePort
	1,  // 11: runtime.Template.GetStat:input_type -> runtime.StatReq
	3,  // 12: runtime.Template.Get:input_type -> runtime.GetTemplateReq
	5,  // 13: runtime.Template.Download:input_type -> runtime.DownloadTemplateReq
	5,  // 14: runtime.Template.DownloadStream:input_type -> runtime.DownloadTemplateReq
	8,  // 15: runtime.Template.Remove:input_type -> runtime.RemoveTemplateReq
	10, // 16: runtime.Template.CleanCache:input_type -> runtime.CleanCacheReq
	2,  // 17: runtime.Template.GetStat:output_type -> runtime.StatResp
	4,  // 18: runtime.Template.Get:output_type -> runtime.GetTemplateResp
	6,  // 19: runtime.Template.Download:output_type -> runtime.DownloadTemplateResp
	7,  // 20: runtime.Template.DownloadStream:output_type -> runtime.DownloadTemplateStreamResp
	9,  // 21: runtime.Template.Remove:output_type -> runtime.RemoveTemplateResp
	11, // 22: runtime.Template.CleanCache:output_type -> runtime.CleanCacheResp
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_template_proto_init() }
func file_template_proto_init() {
	if File_template_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_template_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTemplateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTemplateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadTemplateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadTemplateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadTemplateStreamResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTemplateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTemplateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CleanCacheReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CleanCacheResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplatePort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTemplateResp_TemplateInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTemplateResp_TemplateInfo_LocalUsage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTemplateResp_TemplateInfo_RentUsage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadTemplateReq_DownloadInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadTemplateStreamResp_Progress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_template_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateData_Configuration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_template_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_template_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_template_proto_goTypes,
		DependencyIndexes: file_template_proto_depIdxs,
		EnumInfos:         file_template_proto_enumTypes,
		MessageInfos:      file_template_proto_msgTypes,
	}.Build()
	File_template_proto = out.File
	file_template_proto_rawDesc = nil
	file_template_proto_goTypes = nil
	file_template_proto_depIdxs = nil
}
