// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.28.3
// source: container.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerState_Status int32

const (
	ContainerState_Running   ContainerState_Status = 0
	ContainerState_Launching ContainerState_Status = 1
	ContainerState_Stopped   ContainerState_Status = 2
	ContainerState_Error     ContainerState_Status = 3
)

// Enum value maps for ContainerState_Status.
var (
	ContainerState_Status_name = map[int32]string{
		0: "Running",
		1: "Launching",
		2: "Stopped",
		3: "Error",
	}
	ContainerState_Status_value = map[string]int32{
		"Running":   0,
		"Launching": 1,
		"Stopped":   2,
		"Error":     3,
	}
)

func (x ContainerState_Status) Enum() *ContainerState_Status {
	p := new(ContainerState_Status)
	*p = x
	return p
}

func (x ContainerState_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerState_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_container_proto_enumTypes[0].Descriptor()
}

func (ContainerState_Status) Type() protoreflect.EnumType {
	return &file_container_proto_enumTypes[0]
}

func (x ContainerState_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerState_Status.Descriptor instead.
func (ContainerState_Status) EnumDescriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{4, 0}
}

// will use current template
type ContainerLogsStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// if templateID is empty, will use current
	TemplateID *string `protobuf:"bytes,1,opt,name=templateID,proto3,oneof" json:"templateID,omitempty"`
	// Number of lines from container startup that should be skipped
	Offset uint32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Max number of rows in response
	RowsInResp uint32 `protobuf:"varint,3,opt,name=rows_in_resp,json=rowsInResp,proto3" json:"rows_in_resp,omitempty"`
	// use this param to set count of logs that you need
	// P.S. this will be last logs from container
	Tail *uint32 `protobuf:"varint,4,opt,name=tail,proto3,oneof" json:"tail,omitempty"`
}

func (x *ContainerLogsStreamReq) Reset() {
	*x = ContainerLogsStreamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_container_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerLogsStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerLogsStreamReq) ProtoMessage() {}

func (x *ContainerLogsStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerLogsStreamReq.ProtoReflect.Descriptor instead.
func (*ContainerLogsStreamReq) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerLogsStreamReq) GetTemplateID() string {
	if x != nil && x.TemplateID != nil {
		return *x.TemplateID
	}
	return ""
}

func (x *ContainerLogsStreamReq) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ContainerLogsStreamReq) GetRowsInResp() uint32 {
	if x != nil {
		return x.RowsInResp
	}
	return 0
}

func (x *ContainerLogsStreamReq) GetTail() uint32 {
	if x != nil && x.Tail != nil {
		return *x.Tail
	}
	return 0
}

type ContainerLogs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []string `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *ContainerLogs) Reset() {
	*x = ContainerLogs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_container_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerLogs) ProtoMessage() {}

func (x *ContainerLogs) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerLogs.ProtoReflect.Descriptor instead.
func (*ContainerLogs) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerLogs) GetRows() []string {
	if x != nil {
		return x.Rows
	}
	return nil
}

type ContainerConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options    *ContainerConfiguration_Options `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	TemplateID string                          `protobuf:"bytes,2,opt,name=templateID,proto3" json:"templateID,omitempty"`
}

func (x *ContainerConfiguration) Reset() {
	*x = ContainerConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_container_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerConfiguration) ProtoMessage() {}

func (x *ContainerConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerConfiguration.ProtoReflect.Descriptor instead.
func (*ContainerConfiguration) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{2}
}

func (x *ContainerConfiguration) GetOptions() *ContainerConfiguration_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ContainerConfiguration) GetTemplateID() string {
	if x != nil {
		return x.TemplateID
	}
	return ""
}

type ContainerAuthConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// if enabled, auth will be added to ports that supports authentication
	// see TemplatePort message for more details
	Enabled     bool                                    `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Credentials *ContainerAuthConfiguration_Credentials `protobuf:"bytes,2,opt,name=credentials,proto3,oneof" json:"credentials,omitempty"`
}

func (x *ContainerAuthConfiguration) Reset() {
	*x = ContainerAuthConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_container_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerAuthConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerAuthConfiguration) ProtoMessage() {}

func (x *ContainerAuthConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerAuthConfiguration.ProtoReflect.Descriptor instead.
func (*ContainerAuthConfiguration) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerAuthConfiguration) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ContainerAuthConfiguration) GetCredentials() *ContainerAuthConfiguration_Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type ContainerState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateID   string                       `protobuf:"bytes,1,opt,name=templateID,proto3" json:"templateID,omitempty"` // TemplateID that was used to create the container
	Ports        []*ContainerState_Port       `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	SharedVolume *ContainerState_SharedVolume `protobuf:"bytes,3,opt,name=shared_volume,json=sharedVolume,proto3" json:"shared_volume,omitempty"`
	Status       ContainerState_Status        `protobuf:"varint,4,opt,name=status,proto3,enum=runtime.ContainerState_Status" json:"status,omitempty"`
	StatusMsg    string                       `protobuf:"bytes,5,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"` // Can be useful in error (also "Stopped") case
}

func (x *ContainerState) Reset() {
	*x = ContainerState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_container_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerState) ProtoMessage() {}

func (x *ContainerState) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerState.ProtoReflect.Descriptor instead.
func (*ContainerState) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerState) GetTemplateID() string {
	if x != nil {
		return x.TemplateID
	}
	return ""
}

func (x *ContainerState) GetPorts() []*ContainerState_Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ContainerState) GetSharedVolume() *ContainerState_SharedVolume {
	if x != nil {
		return x.SharedVolume
	}
	return nil
}

func (x *ContainerState) GetStatus() ContainerState_Status {
	if x != nil {
		return x.Status
	}
	return ContainerState_Running
}

func (x *ContainerState) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type ContainerAuthState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled bool                       `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Ports   []*ContainerAuthState_Port `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
}

func (x *ContainerAuthState) Reset() {
	*x = ContainerAuthState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_container_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerAuthState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerAuthState) ProtoMessage() {}

func (x *ContainerAuthState) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerAuthState.ProtoReflect.Descriptor instead.
func (*ContainerAuthState) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerAuthState) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ContainerAuthState) GetPorts() []*ContainerAuthState_Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

type ContainerConfiguration_Options struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// if empty, will be skipped
	SharedVolume *ContainerConfiguration_Options_SharedVolume `protobuf:"bytes,1,opt,name=shared_volume,json=sharedVolume,proto3,oneof" json:"shared_volume,omitempty"`
}

func (x *ContainerConfiguration_Options) Reset() {
	*x = ContainerConfiguration_Options{}
	if protoimpl.UnsafeEnabled {
		mi := &file_container_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerConfiguration_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerConfiguration_Options) ProtoMessage() {}

func (x *ContainerConfiguration_Options) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerConfiguration_Options.ProtoReflect.Descriptor instead.
func (*ContainerConfiguration_Options) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ContainerConfiguration_Options) GetSharedVolume() *ContainerConfiguration_Options_SharedVolume {
	if x != nil {
		return x.SharedVolume
	}
	return nil
}

type ContainerConfiguration_Options_SharedVolume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Credentials *ContainerConfiguration_Options_SharedVolume_Credentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	// mount path in container
	// if empty, will use default
	VolumeMount *string `protobuf:"bytes,2,opt,name=volumeMount,proto3,oneof" json:"volumeMount,omitempty"`
	BucketName  string  `protobuf:"bytes,3,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
}

func (x *ContainerConfiguration_Options_SharedVolume) Reset() {
	*x = ContainerConfiguration_Options_SharedVolume{}
	if protoimpl.UnsafeEnabled {
		mi := &file_container_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerConfiguration_Options_SharedVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerConfiguration_Options_SharedVolume) ProtoMessage() {}

func (x *ContainerConfiguration_Options_SharedVolume) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerConfiguration_Options_SharedVolume.ProtoReflect.Descriptor instead.
func (*ContainerConfiguration_Options_SharedVolume) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *ContainerConfiguration_Options_SharedVolume) GetCredentials() *ContainerConfiguration_Options_SharedVolume_Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ContainerConfiguration_Options_SharedVolume) GetVolumeMount() string {
	if x != nil && x.VolumeMount != nil {
		return *x.VolumeMount
	}
	return ""
}

func (x *ContainerConfiguration_Options_SharedVolume) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

type ContainerConfiguration_Options_SharedVolume_Credentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessKeyID     string `protobuf:"bytes,1,opt,name=accessKeyID,proto3" json:"accessKeyID,omitempty"`
	SecretAccessKey string `protobuf:"bytes,2,opt,name=secretAccessKey,proto3" json:"secretAccessKey,omitempty"`
}

func (x *ContainerConfiguration_Options_SharedVolume_Credentials) Reset() {
	*x = ContainerConfiguration_Options_SharedVolume_Credentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_container_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerConfiguration_Options_SharedVolume_Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerConfiguration_Options_SharedVolume_Credentials) ProtoMessage() {}

func (x *ContainerConfiguration_Options_SharedVolume_Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerConfiguration_Options_SharedVolume_Credentials.ProtoReflect.Descriptor instead.
func (*ContainerConfiguration_Options_SharedVolume_Credentials) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{2, 0, 0, 0}
}

func (x *ContainerConfiguration_Options_SharedVolume_Credentials) GetAccessKeyID() string {
	if x != nil {
		return x.AccessKeyID
	}
	return ""
}

func (x *ContainerConfiguration_Options_SharedVolume_Credentials) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

type ContainerAuthConfiguration_Credentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ContainerAuthConfiguration_Credentials) Reset() {
	*x = ContainerAuthConfiguration_Credentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_container_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerAuthConfiguration_Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerAuthConfiguration_Credentials) ProtoMessage() {}

func (x *ContainerAuthConfiguration_Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerAuthConfiguration_Credentials.ProtoReflect.Descriptor instead.
func (*ContainerAuthConfiguration_Credentials) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ContainerAuthConfiguration_Credentials) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ContainerAuthConfiguration_Credentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ContainerState_SharedVolume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *ContainerState_SharedVolume) Reset() {
	*x = ContainerState_SharedVolume{}
	if protoimpl.UnsafeEnabled {
		mi := &file_container_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerState_SharedVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerState_SharedVolume) ProtoMessage() {}

func (x *ContainerState_SharedVolume) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerState_SharedVolume.ProtoReflect.Descriptor instead.
func (*ContainerState_SharedVolume) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ContainerState_SharedVolume) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ContainerState_Port struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// local_port is the template_port (of course if template image correctly configured)
	// local_port have some transformations:
	//
	//	local_port
	//
	// -> host_port (host port in hypeOS)
	// -> real_port (port after auth proxy (if auth enabled for this port))
	LocalPort string `protobuf:"bytes,1,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"` // not equal to container_port in case of [auth_enabled = true]
	HostPort  string `protobuf:"bytes,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
}

func (x *ContainerState_Port) Reset() {
	*x = ContainerState_Port{}
	if protoimpl.UnsafeEnabled {
		mi := &file_container_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerState_Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerState_Port) ProtoMessage() {}

func (x *ContainerState_Port) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerState_Port.ProtoReflect.Descriptor instead.
func (*ContainerState_Port) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{4, 1}
}

func (x *ContainerState_Port) GetLocalPort() string {
	if x != nil {
		return x.LocalPort
	}
	return ""
}

func (x *ContainerState_Port) GetHostPort() string {
	if x != nil {
		return x.HostPort
	}
	return ""
}

type ContainerAuthState_Port struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InPort  string `protobuf:"bytes,1,opt,name=inPort,proto3" json:"inPort,omitempty"`
	OutPort string `protobuf:"bytes,2,opt,name=outPort,proto3" json:"outPort,omitempty"`
}

func (x *ContainerAuthState_Port) Reset() {
	*x = ContainerAuthState_Port{}
	if protoimpl.UnsafeEnabled {
		mi := &file_container_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerAuthState_Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerAuthState_Port) ProtoMessage() {}

func (x *ContainerAuthState_Port) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerAuthState_Port.ProtoReflect.Descriptor instead.
func (*ContainerAuthState_Port) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ContainerAuthState_Port) GetInPort() string {
	if x != nil {
		return x.InPort
	}
	return ""
}

func (x *ContainerAuthState_Port) GetOutPort() string {
	if x != nil {
		return x.OutPort
	}
	return ""
}

var File_container_proto protoreflect.FileDescriptor

var file_container_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x22, 0xa8, 0x01, 0x0a, 0x16, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x73, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x44, 0x88, 0x01, 0x01, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x72, 0x6f, 0x77, 0x73, 0x5f, 0x69, 0x6e, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x72, 0x6f, 0x77, 0x73, 0x49, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x17, 0x0a, 0x04, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x48, 0x01, 0x52, 0x04, 0x74, 0x61, 0x69, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a,
	0x0b, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x44, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x23, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0xa0, 0x04, 0x0a, 0x16, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x41, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x44, 0x1a, 0xa2, 0x03, 0x0a, 0x07, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x5e, 0x0a, 0x0d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x56, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x56, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x88, 0x01, 0x01, 0x1a, 0xa4, 0x02, 0x0a, 0x0c, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x56,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x62, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x40, 0x2e, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x0b, 0x63, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x25, 0x0a, 0x0b, 0x76, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x88, 0x01, 0x01,
	0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x1a, 0x59, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x49,
	0x44, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x42, 0x0e, 0x0a, 0x0c, 0x5f,
	0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x10, 0x0a, 0x0e, 0x5f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x22, 0xdf, 0x01,
	0x0a, 0x1a, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x56, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x41,
	0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x48, 0x00, 0x52, 0x0b,
	0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x88, 0x01, 0x01, 0x1a, 0x3f,
	0x0a, 0x0b, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x42,
	0x0e, 0x0a, 0x0c, 0x5f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x22,
	0xb2, 0x03, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x49, 0x44, 0x12, 0x32, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x52,
	0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x49, 0x0a, 0x0d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x5f, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x64, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x52, 0x0c, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x56, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1e, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x73, 0x67, 0x1a, 0x28, 0x0a, 0x0c, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x1a, 0x42, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x73,
	0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f,
	0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x3c, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0b, 0x0a, 0x07, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0d, 0x0a,
	0x09, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x53, 0x74, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x10, 0x03, 0x22, 0xa0, 0x01, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x36, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x1a, 0x38, 0x0a,
	0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x50, 0x6f, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6e, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x6f, 0x75, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x75, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x32, 0x59, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x12, 0x4c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x73, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1f, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x73, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x73, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_container_proto_rawDescOnce sync.Once
	file_container_proto_rawDescData = file_container_proto_rawDesc
)

func file_container_proto_rawDescGZIP() []byte {
	file_container_proto_rawDescOnce.Do(func() {
		file_container_proto_rawDescData = protoimpl.X.CompressGZIP(file_container_proto_rawDescData)
	})
	return file_container_proto_rawDescData
}

var file_container_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_container_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_container_proto_goTypes = []interface{}{
	(ContainerState_Status)(0),                                      // 0: runtime.ContainerState.Status
	(*ContainerLogsStreamReq)(nil),                                  // 1: runtime.ContainerLogsStreamReq
	(*ContainerLogs)(nil),                                           // 2: runtime.ContainerLogs
	(*ContainerConfiguration)(nil),                                  // 3: runtime.ContainerConfiguration
	(*ContainerAuthConfiguration)(nil),                              // 4: runtime.ContainerAuthConfiguration
	(*ContainerState)(nil),                                          // 5: runtime.ContainerState
	(*ContainerAuthState)(nil),                                      // 6: runtime.ContainerAuthState
	(*ContainerConfiguration_Options)(nil),                          // 7: runtime.ContainerConfiguration.Options
	(*ContainerConfiguration_Options_SharedVolume)(nil),             // 8: runtime.ContainerConfiguration.Options.SharedVolume
	(*ContainerConfiguration_Options_SharedVolume_Credentials)(nil), // 9: runtime.ContainerConfiguration.Options.SharedVolume.Credentials
	(*ContainerAuthConfiguration_Credentials)(nil),                  // 10: runtime.ContainerAuthConfiguration.Credentials
	(*ContainerState_SharedVolume)(nil),                             // 11: runtime.ContainerState.SharedVolume
	(*ContainerState_Port)(nil),                                     // 12: runtime.ContainerState.Port
	(*ContainerAuthState_Port)(nil),                                 // 13: runtime.ContainerAuthState.Port
}
var file_container_proto_depIdxs = []int32{
	7,  // 0: runtime.ContainerConfiguration.options:type_name -> runtime.ContainerConfiguration.Options
	10, // 1: runtime.ContainerAuthConfiguration.credentials:type_name -> runtime.ContainerAuthConfiguration.Credentials
	12, // 2: runtime.ContainerState.ports:type_name -> runtime.ContainerState.Port
	11, // 3: runtime.ContainerState.shared_volume:type_name -> runtime.ContainerState.SharedVolume
	0,  // 4: runtime.ContainerState.status:type_name -> runtime.ContainerState.Status
	13, // 5: runtime.ContainerAuthState.ports:type_name -> runtime.ContainerAuthState.Port
	8,  // 6: runtime.ContainerConfiguration.Options.shared_volume:type_name -> runtime.ContainerConfiguration.Options.SharedVolume
	9,  // 7: runtime.ContainerConfiguration.Options.SharedVolume.credentials:type_name -> runtime.ContainerConfiguration.Options.SharedVolume.Credentials
	1,  // 8: runtime.Container.GetLogsStream:input_type -> runtime.ContainerLogsStreamReq
	2,  // 9: runtime.Container.GetLogsStream:output_type -> runtime.ContainerLogs
	9,  // [9:10] is the sub-list for method output_type
	8,  // [8:9] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_container_proto_init() }
func file_container_proto_init() {
	if File_container_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_container_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerLogsStreamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_container_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerLogs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_container_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_container_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerAuthConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_container_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_container_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerAuthState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_container_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerConfiguration_Options); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_container_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerConfiguration_Options_SharedVolume); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_container_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerConfiguration_Options_SharedVolume_Credentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_container_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerAuthConfiguration_Credentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_container_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerState_SharedVolume); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_container_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerState_Port); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_container_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerAuthState_Port); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_container_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_container_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_container_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_container_proto_msgTypes[7].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_container_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_container_proto_goTypes,
		DependencyIndexes: file_container_proto_depIdxs,
		EnumInfos:         file_container_proto_enumTypes,
		MessageInfos:      file_container_proto_msgTypes,
	}.Build()
	File_container_proto = out.File
	file_container_proto_rawDesc = nil
	file_container_proto_goTypes = nil
	file_container_proto_depIdxs = nil
}
