// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: container.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Container_GetLogsStream_FullMethodName = "/runtime.Container/GetLogsStream"
)

// ContainerClient is the client API for Container service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContainerClient interface {
	GetLogsStream(ctx context.Context, in *ContainerLogsStreamReq, opts ...grpc.CallOption) (Container_GetLogsStreamClient, error)
}

type containerClient struct {
	cc grpc.ClientConnInterface
}

func NewContainerClient(cc grpc.ClientConnInterface) ContainerClient {
	return &containerClient{cc}
}

func (c *containerClient) GetLogsStream(ctx context.Context, in *ContainerLogsStreamReq, opts ...grpc.CallOption) (Container_GetLogsStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Container_ServiceDesc.Streams[0], Container_GetLogsStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &containerGetLogsStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Container_GetLogsStreamClient interface {
	Recv() (*ContainerLogs, error)
	grpc.ClientStream
}

type containerGetLogsStreamClient struct {
	grpc.ClientStream
}

func (x *containerGetLogsStreamClient) Recv() (*ContainerLogs, error) {
	m := new(ContainerLogs)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ContainerServer is the server API for Container service.
// All implementations must embed UnimplementedContainerServer
// for forward compatibility
type ContainerServer interface {
	GetLogsStream(*ContainerLogsStreamReq, Container_GetLogsStreamServer) error
	mustEmbedUnimplementedContainerServer()
}

// UnimplementedContainerServer must be embedded to have forward compatible implementations.
type UnimplementedContainerServer struct {
}

func (UnimplementedContainerServer) GetLogsStream(*ContainerLogsStreamReq, Container_GetLogsStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetLogsStream not implemented")
}
func (UnimplementedContainerServer) mustEmbedUnimplementedContainerServer() {}

// UnsafeContainerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContainerServer will
// result in compilation errors.
type UnsafeContainerServer interface {
	mustEmbedUnimplementedContainerServer()
}

func RegisterContainerServer(s grpc.ServiceRegistrar, srv ContainerServer) {
	s.RegisterService(&Container_ServiceDesc, srv)
}

func _Container_GetLogsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ContainerLogsStreamReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContainerServer).GetLogsStream(m, &containerGetLogsStreamServer{stream})
}

type Container_GetLogsStreamServer interface {
	Send(*ContainerLogs) error
	grpc.ServerStream
}

type containerGetLogsStreamServer struct {
	grpc.ServerStream
}

func (x *containerGetLogsStreamServer) Send(m *ContainerLogs) error {
	return x.ServerStream.SendMsg(m)
}

// Container_ServiceDesc is the grpc.ServiceDesc for Container service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Container_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.Container",
	HandlerType: (*ContainerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLogsStream",
			Handler:       _Container_GetLogsStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "container.proto",
}
