// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.28.3
// source: hardware.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Storage_DiskType int32

const (
	Storage_UNKNOWN Storage_DiskType = 0
	Storage_HDD     Storage_DiskType = 1
	Storage_FDD     Storage_DiskType = 2
	Storage_ODD     Storage_DiskType = 3
	Storage_SSD     Storage_DiskType = 4
	Storage_VIRTUAL Storage_DiskType = 5
)

// Enum value maps for Storage_DiskType.
var (
	Storage_DiskType_name = map[int32]string{
		0: "UNKNOWN",
		1: "HDD",
		2: "FDD",
		3: "ODD",
		4: "SSD",
		5: "VIRTUAL",
	}
	Storage_DiskType_value = map[string]int32{
		"UNKNOWN": 0,
		"HDD":     1,
		"FDD":     2,
		"ODD":     3,
		"SSD":     4,
		"VIRTUAL": 5,
	}
)

func (x Storage_DiskType) Enum() *Storage_DiskType {
	p := new(Storage_DiskType)
	*p = x
	return p
}

func (x Storage_DiskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Storage_DiskType) Descriptor() protoreflect.EnumDescriptor {
	return file_hardware_proto_enumTypes[0].Descriptor()
}

func (Storage_DiskType) Type() protoreflect.EnumType {
	return &file_hardware_proto_enumTypes[0]
}

func (x Storage_DiskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Storage_DiskType.Descriptor instead.
func (Storage_DiskType) EnumDescriptor() ([]byte, []int) {
	return file_hardware_proto_rawDescGZIP(), []int{5, 0}
}

type SystemInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SystemInfoReq) Reset() {
	*x = SystemInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hardware_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoReq) ProtoMessage() {}

func (x *SystemInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_hardware_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoReq.ProtoReflect.Descriptor instead.
func (*SystemInfoReq) Descriptor() ([]byte, []int) {
	return file_hardware_proto_rawDescGZIP(), []int{0}
}

type SystemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gpu     *GPU     `protobuf:"bytes,2,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Ram     *RAM     `protobuf:"bytes,3,opt,name=ram,proto3" json:"ram,omitempty"`
	Storage *Storage `protobuf:"bytes,4,opt,name=storage,proto3" json:"storage,omitempty"`
	Cpu     *CPU     `protobuf:"bytes,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Network *Network `protobuf:"bytes,6,opt,name=network,proto3" json:"network,omitempty"`
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hardware_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hardware_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_hardware_proto_rawDescGZIP(), []int{1}
}

func (x *SystemInfo) GetGpu() *GPU {
	if x != nil {
		return x.Gpu
	}
	return nil
}

func (x *SystemInfo) GetRam() *RAM {
	if x != nil {
		return x.Ram
	}
	return nil
}

func (x *SystemInfo) GetStorage() *Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *SystemInfo) GetCpu() *CPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *SystemInfo) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

type RAM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalMem float32 `protobuf:"fixed32,1,opt,name=total_mem,json=totalMem,proto3" json:"total_mem,omitempty"` // [KB]
	UsedMem  float32 `protobuf:"fixed32,2,opt,name=used_mem,json=usedMem,proto3" json:"used_mem,omitempty"`    // [KB]
	FreeMem  float32 `protobuf:"fixed32,3,opt,name=free_mem,json=freeMem,proto3" json:"free_mem,omitempty"`    // [KB]
}

func (x *RAM) Reset() {
	*x = RAM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hardware_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RAM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAM) ProtoMessage() {}

func (x *RAM) ProtoReflect() protoreflect.Message {
	mi := &file_hardware_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAM.ProtoReflect.Descriptor instead.
func (*RAM) Descriptor() ([]byte, []int) {
	return file_hardware_proto_rawDescGZIP(), []int{2}
}

func (x *RAM) GetTotalMem() float32 {
	if x != nil {
		return x.TotalMem
	}
	return 0
}

func (x *RAM) GetUsedMem() float32 {
	if x != nil {
		return x.UsedMem
	}
	return 0
}

func (x *RAM) GetFreeMem() float32 {
	if x != nil {
		return x.FreeMem
	}
	return 0
}

type CPU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CoresCount uint32 `protobuf:"varint,2,opt,name=cores_count,json=coresCount,proto3" json:"cores_count,omitempty"`
}

func (x *CPU) Reset() {
	*x = CPU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hardware_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPU) ProtoMessage() {}

func (x *CPU) ProtoReflect() protoreflect.Message {
	mi := &file_hardware_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPU.ProtoReflect.Descriptor instead.
func (*CPU) Descriptor() ([]byte, []int) {
	return file_hardware_proto_rawDescGZIP(), []int{3}
}

func (x *CPU) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CPU) GetCoresCount() uint32 {
	if x != nil {
		return x.CoresCount
	}
	return 0
}

type Network struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping     float32 `protobuf:"fixed32,1,opt,name=ping,proto3" json:"ping,omitempty"`         // [Milliseconds]
	Download float32 `protobuf:"fixed32,2,opt,name=download,proto3" json:"download,omitempty"` // [KBps]
	Upload   float32 `protobuf:"fixed32,3,opt,name=upload,proto3" json:"upload,omitempty"`     // [KBps]
}

func (x *Network) Reset() {
	*x = Network{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hardware_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_hardware_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_hardware_proto_rawDescGZIP(), []int{4}
}

func (x *Network) GetPing() float32 {
	if x != nil {
		return x.Ping
	}
	return 0
}

func (x *Network) GetDownload() float32 {
	if x != nil {
		return x.Download
	}
	return 0
}

func (x *Network) GetUpload() float32 {
	if x != nil {
		return x.Upload
	}
	return 0
}

type Storage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// machine can have different types of disks
	// but this data does not provide what type has what amount of memory
	Types    []Storage_DiskType `protobuf:"varint,1,rep,packed,name=types,proto3,enum=runtime.Storage_DiskType" json:"types,omitempty"`
	TotalMem float32            `protobuf:"fixed32,2,opt,name=total_mem,json=totalMem,proto3" json:"total_mem,omitempty"` // [KB]
	UsedMem  float32            `protobuf:"fixed32,3,opt,name=used_mem,json=usedMem,proto3" json:"used_mem,omitempty"`    // [KB]
	FreeMem  float32            `protobuf:"fixed32,4,opt,name=free_mem,json=freeMem,proto3" json:"free_mem,omitempty"`    // [KB]
}

func (x *Storage) Reset() {
	*x = Storage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hardware_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage) ProtoMessage() {}

func (x *Storage) ProtoReflect() protoreflect.Message {
	mi := &file_hardware_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage.ProtoReflect.Descriptor instead.
func (*Storage) Descriptor() ([]byte, []int) {
	return file_hardware_proto_rawDescGZIP(), []int{5}
}

func (x *Storage) GetTypes() []Storage_DiskType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *Storage) GetTotalMem() float32 {
	if x != nil {
		return x.TotalMem
	}
	return 0
}

func (x *Storage) GetUsedMem() float32 {
	if x != nil {
		return x.UsedMem
	}
	return 0
}

func (x *Storage) GetFreeMem() float32 {
	if x != nil {
		return x.FreeMem
	}
	return 0
}

type GPU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NvidiaDriver *GPU_NvidiaDriver `protobuf:"bytes,1,opt,name=nvidia_driver,json=nvidiaDriver,proto3" json:"nvidia_driver,omitempty"`
	Cards        []*GPU_Card       `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
}

func (x *GPU) Reset() {
	*x = GPU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hardware_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPU) ProtoMessage() {}

func (x *GPU) ProtoReflect() protoreflect.Message {
	mi := &file_hardware_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPU.ProtoReflect.Descriptor instead.
func (*GPU) Descriptor() ([]byte, []int) {
	return file_hardware_proto_rawDescGZIP(), []int{6}
}

func (x *GPU) GetNvidiaDriver() *GPU_NvidiaDriver {
	if x != nil {
		return x.NvidiaDriver
	}
	return nil
}

func (x *GPU) GetCards() []*GPU_Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

type GPU_Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsNvidia bool   `protobuf:"varint,2,opt,name=is_nvidia,json=isNvidia,proto3" json:"is_nvidia,omitempty"`
	// Video memory provided only if card is nvidia and drivers installed
	// (is_nvidia = true & nvidia_driver.installed = true)
	Mem *GPU_Card_VMem `protobuf:"bytes,3,opt,name=mem,proto3,oneof" json:"mem,omitempty"`
}

func (x *GPU_Card) Reset() {
	*x = GPU_Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hardware_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPU_Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPU_Card) ProtoMessage() {}

func (x *GPU_Card) ProtoReflect() protoreflect.Message {
	mi := &file_hardware_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPU_Card.ProtoReflect.Descriptor instead.
func (*GPU_Card) Descriptor() ([]byte, []int) {
	return file_hardware_proto_rawDescGZIP(), []int{6, 0}
}

func (x *GPU_Card) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPU_Card) GetIsNvidia() bool {
	if x != nil {
		return x.IsNvidia
	}
	return false
}

func (x *GPU_Card) GetMem() *GPU_Card_VMem {
	if x != nil {
		return x.Mem
	}
	return nil
}

type GPU_NvidiaDriver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Installed bool   `protobuf:"varint,1,opt,name=installed,proto3" json:"installed,omitempty"`
	Version   string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *GPU_NvidiaDriver) Reset() {
	*x = GPU_NvidiaDriver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hardware_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPU_NvidiaDriver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPU_NvidiaDriver) ProtoMessage() {}

func (x *GPU_NvidiaDriver) ProtoReflect() protoreflect.Message {
	mi := &file_hardware_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPU_NvidiaDriver.ProtoReflect.Descriptor instead.
func (*GPU_NvidiaDriver) Descriptor() ([]byte, []int) {
	return file_hardware_proto_rawDescGZIP(), []int{6, 1}
}

func (x *GPU_NvidiaDriver) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *GPU_NvidiaDriver) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GPU_Card_VMem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total float32 `protobuf:"fixed32,1,opt,name=total,proto3" json:"total,omitempty"` // [KB]
	Used  float32 `protobuf:"fixed32,2,opt,name=used,proto3" json:"used,omitempty"`   // [KB]
	Free  float32 `protobuf:"fixed32,3,opt,name=free,proto3" json:"free,omitempty"`   // [KB]
}

func (x *GPU_Card_VMem) Reset() {
	*x = GPU_Card_VMem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hardware_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GPU_Card_VMem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPU_Card_VMem) ProtoMessage() {}

func (x *GPU_Card_VMem) ProtoReflect() protoreflect.Message {
	mi := &file_hardware_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPU_Card_VMem.ProtoReflect.Descriptor instead.
func (*GPU_Card_VMem) Descriptor() ([]byte, []int) {
	return file_hardware_proto_rawDescGZIP(), []int{6, 0, 0}
}

func (x *GPU_Card_VMem) GetTotal() float32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GPU_Card_VMem) GetUsed() float32 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *GPU_Card_VMem) GetFree() float32 {
	if x != nil {
		return x.Free
	}
	return 0
}

var File_hardware_proto protoreflect.FileDescriptor

var file_hardware_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x22, 0xc4, 0x01, 0x0a, 0x0a, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x03, 0x67, 0x70, 0x75,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x47, 0x50, 0x55, 0x52, 0x03, 0x67, 0x70, 0x75, 0x12, 0x1e, 0x0a, 0x03, 0x72, 0x61, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x52, 0x41, 0x4d, 0x52, 0x03, 0x72, 0x61, 0x6d, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x07, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x43, 0x50, 0x55,
	0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x2a, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x22, 0x58, 0x0a, 0x03, 0x52, 0x41, 0x4d, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x5f, 0x6d, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x6d, 0x65,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x75, 0x73, 0x65, 0x64, 0x4d, 0x65, 0x6d,
	0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x65, 0x65, 0x5f, 0x6d, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x07, 0x66, 0x72, 0x65, 0x65, 0x4d, 0x65, 0x6d, 0x22, 0x3a, 0x0a, 0x03, 0x43,
	0x50, 0x55, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x63, 0x6f, 0x72,
	0x65, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x51, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xd7, 0x01, 0x0a, 0x07, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x6d, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x4d, 0x65, 0x6d, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x75, 0x73, 0x65, 0x64, 0x4d, 0x65, 0x6d, 0x12,
	0x19, 0x0a, 0x08, 0x66, 0x72, 0x65, 0x65, 0x5f, 0x6d, 0x65, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x07, 0x66, 0x72, 0x65, 0x65, 0x4d, 0x65, 0x6d, 0x22, 0x48, 0x0a, 0x08, 0x44, 0x69,
	0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x48, 0x44, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03,
	0x46, 0x44, 0x44, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x44, 0x44, 0x10, 0x03, 0x12, 0x07,
	0x0a, 0x03, 0x53, 0x53, 0x44, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x56, 0x49, 0x52, 0x54, 0x55,
	0x41, 0x4c, 0x10, 0x05, 0x22, 0xed, 0x02, 0x0a, 0x03, 0x47, 0x50, 0x55, 0x12, 0x3e, 0x0a, 0x0d,
	0x6e, 0x76, 0x69, 0x64, 0x69, 0x61, 0x5f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x47, 0x50,
	0x55, 0x2e, 0x4e, 0x76, 0x69, 0x64, 0x69, 0x61, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x52, 0x0c,
	0x6e, 0x76, 0x69, 0x64, 0x69, 0x61, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x05,
	0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x47, 0x50, 0x55, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x05,
	0x63, 0x61, 0x72, 0x64, 0x73, 0x1a, 0xb4, 0x01, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6e, 0x76, 0x69, 0x64, 0x69, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4e, 0x76, 0x69, 0x64, 0x69, 0x61, 0x12,
	0x2d, 0x0a, 0x03, 0x6d, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x47, 0x50, 0x55, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x2e,
	0x56, 0x4d, 0x65, 0x6d, 0x48, 0x00, 0x52, 0x03, 0x6d, 0x65, 0x6d, 0x88, 0x01, 0x01, 0x1a, 0x44,
	0x0a, 0x04, 0x56, 0x4d, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x75, 0x73, 0x65, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04,
	0x66, 0x72, 0x65, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6d, 0x65, 0x6d, 0x1a, 0x46, 0x0a, 0x0c,
	0x4e, 0x76, 0x69, 0x64, 0x69, 0x61, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_hardware_proto_rawDescOnce sync.Once
	file_hardware_proto_rawDescData = file_hardware_proto_rawDesc
)

func file_hardware_proto_rawDescGZIP() []byte {
	file_hardware_proto_rawDescOnce.Do(func() {
		file_hardware_proto_rawDescData = protoimpl.X.CompressGZIP(file_hardware_proto_rawDescData)
	})
	return file_hardware_proto_rawDescData
}

var file_hardware_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hardware_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_hardware_proto_goTypes = []interface{}{
	(Storage_DiskType)(0),    // 0: runtime.Storage.DiskType
	(*SystemInfoReq)(nil),    // 1: runtime.SystemInfoReq
	(*SystemInfo)(nil),       // 2: runtime.SystemInfo
	(*RAM)(nil),              // 3: runtime.RAM
	(*CPU)(nil),              // 4: runtime.CPU
	(*Network)(nil),          // 5: runtime.Network
	(*Storage)(nil),          // 6: runtime.Storage
	(*GPU)(nil),              // 7: runtime.GPU
	(*GPU_Card)(nil),         // 8: runtime.GPU.Card
	(*GPU_NvidiaDriver)(nil), // 9: runtime.GPU.NvidiaDriver
	(*GPU_Card_VMem)(nil),    // 10: runtime.GPU.Card.VMem
}
var file_hardware_proto_depIdxs = []int32{
	7,  // 0: runtime.SystemInfo.gpu:type_name -> runtime.GPU
	3,  // 1: runtime.SystemInfo.ram:type_name -> runtime.RAM
	6,  // 2: runtime.SystemInfo.storage:type_name -> runtime.Storage
	4,  // 3: runtime.SystemInfo.cpu:type_name -> runtime.CPU
	5,  // 4: runtime.SystemInfo.network:type_name -> runtime.Network
	0,  // 5: runtime.Storage.types:type_name -> runtime.Storage.DiskType
	9,  // 6: runtime.GPU.nvidia_driver:type_name -> runtime.GPU.NvidiaDriver
	8,  // 7: runtime.GPU.cards:type_name -> runtime.GPU.Card
	10, // 8: runtime.GPU.Card.mem:type_name -> runtime.GPU.Card.VMem
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_hardware_proto_init() }
func file_hardware_proto_init() {
	if File_hardware_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hardware_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hardware_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hardware_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RAM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hardware_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CPU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hardware_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Network); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hardware_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Storage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hardware_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hardware_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPU_Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hardware_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPU_NvidiaDriver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hardware_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GPU_Card_VMem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_hardware_proto_msgTypes[7].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hardware_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hardware_proto_goTypes,
		DependencyIndexes: file_hardware_proto_depIdxs,
		EnumInfos:         file_hardware_proto_enumTypes,
		MessageInfos:      file_hardware_proto_msgTypes,
	}.Build()
	File_hardware_proto = out.File
	file_hardware_proto_rawDesc = nil
	file_hardware_proto_goTypes = nil
	file_hardware_proto_depIdxs = nil
}
