// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.29.3
// source: network.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkState_Status int32

const (
	NetworkState_Ok        NetworkState_Status = 0
	NetworkState_Launching NetworkState_Status = 1
	NetworkState_Error     NetworkState_Status = 2
)

// Enum value maps for NetworkState_Status.
var (
	NetworkState_Status_name = map[int32]string{
		0: "Ok",
		1: "Launching",
		2: "Error",
	}
	NetworkState_Status_value = map[string]int32{
		"Ok":        0,
		"Launching": 1,
		"Error":     2,
	}
)

func (x NetworkState_Status) Enum() *NetworkState_Status {
	p := new(NetworkState_Status)
	*p = x
	return p
}

func (x NetworkState_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkState_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[0].Descriptor()
}

func (NetworkState_Status) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[0]
}

func (x NetworkState_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkState_Status.Descriptor instead.
func (NetworkState_Status) EnumDescriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{1, 0}
}

type TailscaleState_Status int32

const (
	TailscaleState_Running TailscaleState_Status = 0
	TailscaleState_Stopped TailscaleState_Status = 1
)

// Enum value maps for TailscaleState_Status.
var (
	TailscaleState_Status_name = map[int32]string{
		0: "Running",
		1: "Stopped",
	}
	TailscaleState_Status_value = map[string]int32{
		"Running": 0,
		"Stopped": 1,
	}
)

func (x TailscaleState_Status) Enum() *TailscaleState_Status {
	p := new(TailscaleState_Status)
	*p = x
	return p
}

func (x TailscaleState_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TailscaleState_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[1].Descriptor()
}

func (TailscaleState_Status) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[1]
}

func (x TailscaleState_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TailscaleState_Status.Descriptor instead.
func (TailscaleState_Status) EnumDescriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{4, 0}
}

type PikoState_Status int32

const (
	PikoState_Running PikoState_Status = 0
	PikoState_Stopped PikoState_Status = 1
	PikoState_Error   PikoState_Status = 2
)

// Enum value maps for PikoState_Status.
var (
	PikoState_Status_name = map[int32]string{
		0: "Running",
		1: "Stopped",
		2: "Error",
	}
	PikoState_Status_value = map[string]int32{
		"Running": 0,
		"Stopped": 1,
		"Error":   2,
	}
)

func (x PikoState_Status) Enum() *PikoState_Status {
	p := new(PikoState_Status)
	*p = x
	return p
}

func (x PikoState_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PikoState_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[2].Descriptor()
}

func (PikoState_Status) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[2]
}

func (x PikoState_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PikoState_Status.Descriptor instead.
func (PikoState_Status) EnumDescriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{7, 0}
}

// Data for connect (used in change mode request)
type NetworkConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// piko and tailscale are optional here, because only one of them can be used
	// P.S. one of them is required
	Tailscale *TailscaleConfiguration `protobuf:"bytes,1,opt,name=tailscale,proto3,oneof" json:"tailscale,omitempty"` // required in [Host_P2P_VM, Client_P2P_VM]
	Piko      *PikoConfiguration      `protobuf:"bytes,2,opt,name=piko,proto3,oneof" json:"piko,omitempty"`           // required in [Host_P2P_VM_Proxy]
}

func (x *NetworkConfiguration) Reset() {
	*x = NetworkConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfiguration) ProtoMessage() {}

func (x *NetworkConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfiguration.ProtoReflect.Descriptor instead.
func (*NetworkConfiguration) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkConfiguration) GetTailscale() *TailscaleConfiguration {
	if x != nil {
		return x.Tailscale
	}
	return nil
}

func (x *NetworkConfiguration) GetPiko() *PikoConfiguration {
	if x != nil {
		return x.Piko
	}
	return nil
}

type NetworkState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tailscale    *TailscaleState      `protobuf:"bytes,1,opt,name=tailscale,proto3" json:"tailscale,omitempty"`
	Piko         *PikoState           `protobuf:"bytes,2,opt,name=piko,proto3" json:"piko,omitempty"`
	Iptables     *IptablesState       `protobuf:"bytes,3,opt,name=iptables,proto3" json:"iptables,omitempty"`
	ExposedPorts []*NetworkState_Port `protobuf:"bytes,4,rep,name=exposed_ports,json=exposedPorts,proto3" json:"exposed_ports,omitempty"`
	Status       NetworkState_Status  `protobuf:"varint,5,opt,name=status,proto3,enum=runtime.NetworkState_Status" json:"status,omitempty"`
	StatusMsg    string               `protobuf:"bytes,6,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
}

func (x *NetworkState) Reset() {
	*x = NetworkState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkState) ProtoMessage() {}

func (x *NetworkState) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkState.ProtoReflect.Descriptor instead.
func (*NetworkState) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkState) GetTailscale() *TailscaleState {
	if x != nil {
		return x.Tailscale
	}
	return nil
}

func (x *NetworkState) GetPiko() *PikoState {
	if x != nil {
		return x.Piko
	}
	return nil
}

func (x *NetworkState) GetIptables() *IptablesState {
	if x != nil {
		return x.Iptables
	}
	return nil
}

func (x *NetworkState) GetExposedPorts() []*NetworkState_Port {
	if x != nil {
		return x.ExposedPorts
	}
	return nil
}

func (x *NetworkState) GetStatus() NetworkState_Status {
	if x != nil {
		return x.Status
	}
	return NetworkState_Ok
}

func (x *NetworkState) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type NetworkInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tailscale *TailscaleInfo `protobuf:"bytes,1,opt,name=tailscale,proto3" json:"tailscale,omitempty"`
	Piko      *PikoInfo      `protobuf:"bytes,2,opt,name=piko,proto3" json:"piko,omitempty"`
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkInfo) GetTailscale() *TailscaleInfo {
	if x != nil {
		return x.Tailscale
	}
	return nil
}

func (x *NetworkInfo) GetPiko() *PikoInfo {
	if x != nil {
		return x.Piko
	}
	return nil
}

type TailscaleConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AuthKey  string `protobuf:"bytes,2,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
}

func (x *TailscaleConfiguration) Reset() {
	*x = TailscaleConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TailscaleConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailscaleConfiguration) ProtoMessage() {}

func (x *TailscaleConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailscaleConfiguration.ProtoReflect.Descriptor instead.
func (*TailscaleConfiguration) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{3}
}

func (x *TailscaleConfiguration) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TailscaleConfiguration) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

type TailscaleState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hosted        bool                  `protobuf:"varint,1,opt,name=hosted,proto3" json:"hosted,omitempty"`
	Ips           []*TailscaleState_Ip  `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
	PeerHostnames []string              `protobuf:"bytes,3,rep,name=peer_hostnames,json=peerHostnames,proto3" json:"peer_hostnames,omitempty"`
	Status        TailscaleState_Status `protobuf:"varint,4,opt,name=status,proto3,enum=runtime.TailscaleState_Status" json:"status,omitempty"`
	StatusMsg     string                `protobuf:"bytes,5,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
}

func (x *TailscaleState) Reset() {
	*x = TailscaleState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TailscaleState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailscaleState) ProtoMessage() {}

func (x *TailscaleState) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailscaleState.ProtoReflect.Descriptor instead.
func (*TailscaleState) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{4}
}

func (x *TailscaleState) GetHosted() bool {
	if x != nil {
		return x.Hosted
	}
	return false
}

func (x *TailscaleState) GetIps() []*TailscaleState_Ip {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *TailscaleState) GetPeerHostnames() []string {
	if x != nil {
		return x.PeerHostnames
	}
	return nil
}

func (x *TailscaleState) GetStatus() TailscaleState_Status {
	if x != nil {
		return x.Status
	}
	return TailscaleState_Running
}

func (x *TailscaleState) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type TailscaleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Available bool   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Version   string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *TailscaleInfo) Reset() {
	*x = TailscaleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TailscaleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailscaleInfo) ProtoMessage() {}

func (x *TailscaleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailscaleInfo.ProtoReflect.Descriptor instead.
func (*TailscaleInfo) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{5}
}

func (x *TailscaleInfo) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *TailscaleInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PikoConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoints []*PikoConfiguration_Endpoint `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	AuthKey   string                        `protobuf:"bytes,2,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
}

func (x *PikoConfiguration) Reset() {
	*x = PikoConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PikoConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PikoConfiguration) ProtoMessage() {}

func (x *PikoConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PikoConfiguration.ProtoReflect.Descriptor instead.
func (*PikoConfiguration) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{6}
}

func (x *PikoConfiguration) GetEndpoints() []*PikoConfiguration_Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *PikoConfiguration) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

type PikoState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoints []*PikoState_Endpoint `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Status    PikoState_Status      `protobuf:"varint,3,opt,name=status,proto3,enum=runtime.PikoState_Status" json:"status,omitempty"`
	StatusMsg string                `protobuf:"bytes,4,opt,name=status_msg,json=statusMsg,proto3" json:"status_msg,omitempty"`
}

func (x *PikoState) Reset() {
	*x = PikoState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PikoState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PikoState) ProtoMessage() {}

func (x *PikoState) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PikoState.ProtoReflect.Descriptor instead.
func (*PikoState) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{7}
}

func (x *PikoState) GetEndpoints() []*PikoState_Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *PikoState) GetStatus() PikoState_Status {
	if x != nil {
		return x.Status
	}
	return PikoState_Running
}

func (x *PikoState) GetStatusMsg() string {
	if x != nil {
		return x.StatusMsg
	}
	return ""
}

type PikoInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Available bool   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Version   string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *PikoInfo) Reset() {
	*x = PikoInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PikoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PikoInfo) ProtoMessage() {}

func (x *PikoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PikoInfo.ProtoReflect.Descriptor instead.
func (*PikoInfo) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{8}
}

func (x *PikoInfo) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *PikoInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type IptablesState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// configured - is configured correctly
	// (enabled when is needed, and disabled when is not needed)
	// so it always true in correct case
	Configured bool `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
}

func (x *IptablesState) Reset() {
	*x = IptablesState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IptablesState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IptablesState) ProtoMessage() {}

func (x *IptablesState) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IptablesState.ProtoReflect.Descriptor instead.
func (*IptablesState) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{9}
}

func (x *IptablesState) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

type NetworkState_Port struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string       `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Port     string       `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol PortProtocol `protobuf:"varint,3,opt,name=protocol,proto3,enum=runtime.PortProtocol" json:"protocol,omitempty"`
}

func (x *NetworkState_Port) Reset() {
	*x = NetworkState_Port{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkState_Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkState_Port) ProtoMessage() {}

func (x *NetworkState_Port) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkState_Port.ProtoReflect.Descriptor instead.
func (*NetworkState_Port) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{1, 0}
}

func (x *NetworkState_Port) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NetworkState_Port) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *NetworkState_Port) GetProtocol() PortProtocol {
	if x != nil {
		return x.Protocol
	}
	return PortProtocol_HTTP
}

type TailscaleState_Ip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ipv4 string `protobuf:"bytes,1,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6 string `protobuf:"bytes,2,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
}

func (x *TailscaleState_Ip) Reset() {
	*x = TailscaleState_Ip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TailscaleState_Ip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailscaleState_Ip) ProtoMessage() {}

func (x *TailscaleState_Ip) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailscaleState_Ip.ProtoReflect.Descriptor instead.
func (*TailscaleState_Ip) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{4, 0}
}

func (x *TailscaleState_Ip) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *TailscaleState_Ip) GetIpv6() string {
	if x != nil {
		return x.Ipv6
	}
	return ""
}

type PikoConfiguration_Endpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// template_port used like template portID here
	// to know for which port (from template) is this endpoint
	TemplatePort string `protobuf:"bytes,1,opt,name=template_port,json=templatePort,proto3" json:"template_port,omitempty"`
	// endpoint name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PikoConfiguration_Endpoint) Reset() {
	*x = PikoConfiguration_Endpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PikoConfiguration_Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PikoConfiguration_Endpoint) ProtoMessage() {}

func (x *PikoConfiguration_Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PikoConfiguration_Endpoint.ProtoReflect.Descriptor instead.
func (*PikoConfiguration_Endpoint) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{6, 0}
}

func (x *PikoConfiguration_Endpoint) GetTemplatePort() string {
	if x != nil {
		return x.TemplatePort
	}
	return ""
}

func (x *PikoConfiguration_Endpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PikoState_Endpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// template_port used like template portID here
	// to know for which port (from template) is this endpoint
	TemplatePort string `protobuf:"bytes,1,opt,name=template_port,json=templatePort,proto3" json:"template_port,omitempty"`
	// proxied_port is the real proxied port
	// because template port (local container port) can be changed
	//
	//	template_port (local port in docker)
	//
	// -> host_container_port (host port in hypeOS)
	// -> real_port (host port after auth proxy (if auth enabled))
	// so proxied_port is real_port that piko proxied
	ProxiedPort string `protobuf:"bytes,2,opt,name=proxied_port,json=proxiedPort,proto3" json:"proxied_port,omitempty"`
	// result link for this endpoint
	Link string `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	// endpoint name, that used to this port
	Name     string       `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Protocol PortProtocol `protobuf:"varint,5,opt,name=protocol,proto3,enum=runtime.PortProtocol" json:"protocol,omitempty"`
}

func (x *PikoState_Endpoint) Reset() {
	*x = PikoState_Endpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PikoState_Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PikoState_Endpoint) ProtoMessage() {}

func (x *PikoState_Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PikoState_Endpoint.ProtoReflect.Descriptor instead.
func (*PikoState_Endpoint) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{7, 0}
}

func (x *PikoState_Endpoint) GetTemplatePort() string {
	if x != nil {
		return x.TemplatePort
	}
	return ""
}

func (x *PikoState_Endpoint) GetProxiedPort() string {
	if x != nil {
		return x.ProxiedPort
	}
	return ""
}

func (x *PikoState_Endpoint) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *PikoState_Endpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PikoState_Endpoint) GetProtocol() PortProtocol {
	if x != nil {
		return x.Protocol
	}
	return PortProtocol_HTTP
}

var File_network_proto protoreflect.FileDescriptor

var file_network_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x1a, 0x0e, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x01, 0x0a, 0x14, 0x4e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x42, 0x0a, 0x09, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x54,
	0x61, 0x69, 0x6c, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x09, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x63, 0x61,
	0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x33, 0x0a, 0x04, 0x70, 0x69, 0x6b, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x50, 0x69,
	0x6b, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x01, 0x52, 0x04, 0x70, 0x69, 0x6b, 0x6f, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x70, 0x69, 0x6b,
	0x6f, 0x22, 0xc8, 0x03, 0x0a, 0x0c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x35, 0x0a, 0x09, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x54, 0x61, 0x69, 0x6c, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x09,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x70, 0x69, 0x6b,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x50, 0x69, 0x6b, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x04, 0x70, 0x69, 0x6b,
	0x6f, 0x12, 0x32, 0x0a, 0x08, 0x69, 0x70, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x49, 0x70,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x08, 0x69, 0x70, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x0d, 0x65, 0x78, 0x70, 0x6f, 0x73, 0x65, 0x64,
	0x5f, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x0c, 0x65, 0x78, 0x70, 0x6f, 0x73, 0x65,
	0x64, 0x50, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x73, 0x67, 0x1a, 0x63, 0x0a, 0x04, 0x50,
	0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x31, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x15, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x22, 0x2a, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x10,
	0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x02, 0x22, 0x6a, 0x0a, 0x0b,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x34, 0x0a, 0x09, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x54, 0x61, 0x69, 0x6c, 0x73, 0x63, 0x61,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x63, 0x61, 0x6c,
	0x65, 0x12, 0x25, 0x0a, 0x04, 0x70, 0x69, 0x6b, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x50, 0x69, 0x6b, 0x6f, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x04, 0x70, 0x69, 0x6b, 0x6f, 0x22, 0x50, 0x0a, 0x16, 0x54, 0x61, 0x69, 0x6c,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x4b, 0x65, 0x79, 0x22, 0xa6, 0x02, 0x0a, 0x0e, 0x54,
	0x61, 0x69, 0x6c, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x6f, 0x73, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x68,
	0x6f, 0x73, 0x74, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x03, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x54, 0x61, 0x69,
	0x6c, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x49, 0x70, 0x52, 0x03,
	0x69, 0x70, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x68, 0x6f, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x65, 0x65,
	0x72, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x72, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x2e, 0x54, 0x61, 0x69, 0x6c, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x6d, 0x73, 0x67,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x73,
	0x67, 0x1a, 0x2c, 0x0a, 0x02, 0x49, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x70, 0x76, 0x34, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x70, 0x76, 0x34, 0x12, 0x12, 0x0a, 0x04, 0x69,
	0x70, 0x76, 0x36, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x70, 0x76, 0x36, 0x22,
	0x22, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x75, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x70, 0x70, 0x65,
	0x64, 0x10, 0x01, 0x22, 0x47, 0x0a, 0x0d, 0x54, 0x61, 0x69, 0x6c, 0x73, 0x63, 0x61, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xb6, 0x01, 0x0a,
	0x11, 0x50, 0x69, 0x6b, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x41, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x50, 0x69, 0x6b, 0x6f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x4b, 0x65, 0x79,
	0x1a, 0x43, 0x0a, 0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d,
	0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x72,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xf7, 0x02, 0x0a, 0x09, 0x50, 0x69, 0x6b, 0x6f, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x39, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x50, 0x69, 0x6b, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x31,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19,
	0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x50, 0x69, 0x6b, 0x6f, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x6d, 0x73, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x73, 0x67,
	0x1a, 0xad, 0x01, 0x0a, 0x08, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x23, 0x0a,
	0x0d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x65, 0x64, 0x5f, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x78, 0x69, 0x65,
	0x64, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x15, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x22, 0x2d, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x75,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x70, 0x70,
	0x65, 0x64, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x02, 0x22,
	0x42, 0x0a, 0x08, 0x50, 0x69, 0x6b, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x61,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x2f, 0x0a, 0x0d, 0x49, 0x70, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x65, 0x64, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_network_proto_rawDescOnce sync.Once
	file_network_proto_rawDescData = file_network_proto_rawDesc
)

func file_network_proto_rawDescGZIP() []byte {
	file_network_proto_rawDescOnce.Do(func() {
		file_network_proto_rawDescData = protoimpl.X.CompressGZIP(file_network_proto_rawDescData)
	})
	return file_network_proto_rawDescData
}

var file_network_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_network_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_network_proto_goTypes = []interface{}{
	(NetworkState_Status)(0),           // 0: runtime.NetworkState.Status
	(TailscaleState_Status)(0),         // 1: runtime.TailscaleState.Status
	(PikoState_Status)(0),              // 2: runtime.PikoState.Status
	(*NetworkConfiguration)(nil),       // 3: runtime.NetworkConfiguration
	(*NetworkState)(nil),               // 4: runtime.NetworkState
	(*NetworkInfo)(nil),                // 5: runtime.NetworkInfo
	(*TailscaleConfiguration)(nil),     // 6: runtime.TailscaleConfiguration
	(*TailscaleState)(nil),             // 7: runtime.TailscaleState
	(*TailscaleInfo)(nil),              // 8: runtime.TailscaleInfo
	(*PikoConfiguration)(nil),          // 9: runtime.PikoConfiguration
	(*PikoState)(nil),                  // 10: runtime.PikoState
	(*PikoInfo)(nil),                   // 11: runtime.PikoInfo
	(*IptablesState)(nil),              // 12: runtime.IptablesState
	(*NetworkState_Port)(nil),          // 13: runtime.NetworkState.Port
	(*TailscaleState_Ip)(nil),          // 14: runtime.TailscaleState.Ip
	(*PikoConfiguration_Endpoint)(nil), // 15: runtime.PikoConfiguration.Endpoint
	(*PikoState_Endpoint)(nil),         // 16: runtime.PikoState.Endpoint
	(PortProtocol)(0),                  // 17: runtime.PortProtocol
}
var file_network_proto_depIdxs = []int32{
	6,  // 0: runtime.NetworkConfiguration.tailscale:type_name -> runtime.TailscaleConfiguration
	9,  // 1: runtime.NetworkConfiguration.piko:type_name -> runtime.PikoConfiguration
	7,  // 2: runtime.NetworkState.tailscale:type_name -> runtime.TailscaleState
	10, // 3: runtime.NetworkState.piko:type_name -> runtime.PikoState
	12, // 4: runtime.NetworkState.iptables:type_name -> runtime.IptablesState
	13, // 5: runtime.NetworkState.exposed_ports:type_name -> runtime.NetworkState.Port
	0,  // 6: runtime.NetworkState.status:type_name -> runtime.NetworkState.Status
	8,  // 7: runtime.NetworkInfo.tailscale:type_name -> runtime.TailscaleInfo
	11, // 8: runtime.NetworkInfo.piko:type_name -> runtime.PikoInfo
	14, // 9: runtime.TailscaleState.ips:type_name -> runtime.TailscaleState.Ip
	1,  // 10: runtime.TailscaleState.status:type_name -> runtime.TailscaleState.Status
	15, // 11: runtime.PikoConfiguration.endpoints:type_name -> runtime.PikoConfiguration.Endpoint
	16, // 12: runtime.PikoState.endpoints:type_name -> runtime.PikoState.Endpoint
	2,  // 13: runtime.PikoState.status:type_name -> runtime.PikoState.Status
	17, // 14: runtime.NetworkState.Port.protocol:type_name -> runtime.PortProtocol
	17, // 15: runtime.PikoState.Endpoint.protocol:type_name -> runtime.PortProtocol
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_network_proto_init() }
func file_network_proto_init() {
	if File_network_proto != nil {
		return
	}
	file_template_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_network_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TailscaleConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TailscaleState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TailscaleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PikoConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PikoState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PikoInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IptablesState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkState_Port); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TailscaleState_Ip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PikoConfiguration_Endpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PikoState_Endpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_network_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_network_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_network_proto_goTypes,
		DependencyIndexes: file_network_proto_depIdxs,
		EnumInfos:         file_network_proto_enumTypes,
		MessageInfos:      file_network_proto_msgTypes,
	}.Build()
	File_network_proto = out.File
	file_network_proto_rawDesc = nil
	file_network_proto_goTypes = nil
	file_network_proto_depIdxs = nil
}
