// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: template.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Template_GetStat_FullMethodName        = "/runtime.Template/GetStat"
	Template_Get_FullMethodName            = "/runtime.Template/Get"
	Template_Download_FullMethodName       = "/runtime.Template/Download"
	Template_DownloadStream_FullMethodName = "/runtime.Template/DownloadStream"
	Template_Remove_FullMethodName         = "/runtime.Template/Remove"
	Template_CleanCache_FullMethodName     = "/runtime.Template/CleanCache"
)

// TemplateClient is the client API for Template service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemplateClient interface {
	GetStat(ctx context.Context, in *StatReq, opts ...grpc.CallOption) (*StatResp, error)
	// List of available containers (images that already pulled and running)
	Get(ctx context.Context, in *GetTemplateReq, opts ...grpc.CallOption) (*GetTemplateResp, error)
	Download(ctx context.Context, in *DownloadTemplateReq, opts ...grpc.CallOption) (*DownloadTemplateResp, error)
	DownloadStream(ctx context.Context, in *DownloadTemplateReq, opts ...grpc.CallOption) (Template_DownloadStreamClient, error)
	Remove(ctx context.Context, in *RemoveTemplateReq, opts ...grpc.CallOption) (*RemoveTemplateResp, error)
	CleanCache(ctx context.Context, in *CleanCacheReq, opts ...grpc.CallOption) (*CleanCacheResp, error)
}

type templateClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplateClient(cc grpc.ClientConnInterface) TemplateClient {
	return &templateClient{cc}
}

func (c *templateClient) GetStat(ctx context.Context, in *StatReq, opts ...grpc.CallOption) (*StatResp, error) {
	out := new(StatResp)
	err := c.cc.Invoke(ctx, Template_GetStat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateClient) Get(ctx context.Context, in *GetTemplateReq, opts ...grpc.CallOption) (*GetTemplateResp, error) {
	out := new(GetTemplateResp)
	err := c.cc.Invoke(ctx, Template_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateClient) Download(ctx context.Context, in *DownloadTemplateReq, opts ...grpc.CallOption) (*DownloadTemplateResp, error) {
	out := new(DownloadTemplateResp)
	err := c.cc.Invoke(ctx, Template_Download_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateClient) DownloadStream(ctx context.Context, in *DownloadTemplateReq, opts ...grpc.CallOption) (Template_DownloadStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Template_ServiceDesc.Streams[0], Template_DownloadStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &templateDownloadStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Template_DownloadStreamClient interface {
	Recv() (*DownloadTemplateStreamResp, error)
	grpc.ClientStream
}

type templateDownloadStreamClient struct {
	grpc.ClientStream
}

func (x *templateDownloadStreamClient) Recv() (*DownloadTemplateStreamResp, error) {
	m := new(DownloadTemplateStreamResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *templateClient) Remove(ctx context.Context, in *RemoveTemplateReq, opts ...grpc.CallOption) (*RemoveTemplateResp, error) {
	out := new(RemoveTemplateResp)
	err := c.cc.Invoke(ctx, Template_Remove_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateClient) CleanCache(ctx context.Context, in *CleanCacheReq, opts ...grpc.CallOption) (*CleanCacheResp, error) {
	out := new(CleanCacheResp)
	err := c.cc.Invoke(ctx, Template_CleanCache_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplateServer is the server API for Template service.
// All implementations must embed UnimplementedTemplateServer
// for forward compatibility
type TemplateServer interface {
	GetStat(context.Context, *StatReq) (*StatResp, error)
	// List of available containers (images that already pulled and running)
	Get(context.Context, *GetTemplateReq) (*GetTemplateResp, error)
	Download(context.Context, *DownloadTemplateReq) (*DownloadTemplateResp, error)
	DownloadStream(*DownloadTemplateReq, Template_DownloadStreamServer) error
	Remove(context.Context, *RemoveTemplateReq) (*RemoveTemplateResp, error)
	CleanCache(context.Context, *CleanCacheReq) (*CleanCacheResp, error)
	mustEmbedUnimplementedTemplateServer()
}

// UnimplementedTemplateServer must be embedded to have forward compatible implementations.
type UnimplementedTemplateServer struct {
}

func (UnimplementedTemplateServer) GetStat(context.Context, *StatReq) (*StatResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStat not implemented")
}
func (UnimplementedTemplateServer) Get(context.Context, *GetTemplateReq) (*GetTemplateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTemplateServer) Download(context.Context, *DownloadTemplateReq) (*DownloadTemplateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedTemplateServer) DownloadStream(*DownloadTemplateReq, Template_DownloadStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadStream not implemented")
}
func (UnimplementedTemplateServer) Remove(context.Context, *RemoveTemplateReq) (*RemoveTemplateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedTemplateServer) CleanCache(context.Context, *CleanCacheReq) (*CleanCacheResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanCache not implemented")
}
func (UnimplementedTemplateServer) mustEmbedUnimplementedTemplateServer() {}

// UnsafeTemplateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplateServer will
// result in compilation errors.
type UnsafeTemplateServer interface {
	mustEmbedUnimplementedTemplateServer()
}

func RegisterTemplateServer(s grpc.ServiceRegistrar, srv TemplateServer) {
	s.RegisterService(&Template_ServiceDesc, srv)
}

func _Template_GetStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).GetStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Template_GetStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).GetStat(ctx, req.(*StatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Template_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Template_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).Get(ctx, req.(*GetTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Template_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).Download(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Template_Download_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).Download(ctx, req.(*DownloadTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Template_DownloadStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadTemplateReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TemplateServer).DownloadStream(m, &templateDownloadStreamServer{stream})
}

type Template_DownloadStreamServer interface {
	Send(*DownloadTemplateStreamResp) error
	grpc.ServerStream
}

type templateDownloadStreamServer struct {
	grpc.ServerStream
}

func (x *templateDownloadStreamServer) Send(m *DownloadTemplateStreamResp) error {
	return x.ServerStream.SendMsg(m)
}

func _Template_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Template_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).Remove(ctx, req.(*RemoveTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Template_CleanCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanCacheReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServer).CleanCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Template_CleanCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServer).CleanCache(ctx, req.(*CleanCacheReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Template_ServiceDesc is the grpc.ServiceDesc for Template service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Template_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.Template",
	HandlerType: (*TemplateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStat",
			Handler:    _Template_GetStat_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Template_Get_Handler,
		},
		{
			MethodName: "Download",
			Handler:    _Template_Download_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Template_Remove_Handler,
		},
		{
			MethodName: "CleanCache",
			Handler:    _Template_CleanCache_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadStream",
			Handler:       _Template_DownloadStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "template.proto",
}
