// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: worker.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Worker_ChangeMode_FullMethodName     = "/runtime.Worker/ChangeMode"
	Worker_ExecuteEvent_FullMethodName   = "/runtime.Worker/ExecuteEvent"
	Worker_GetStateStream_FullMethodName = "/runtime.Worker/GetStateStream"
	Worker_GetSysInfo_FullMethodName     = "/runtime.Worker/GetSysInfo"
	Worker_GetInfo_FullMethodName        = "/runtime.Worker/GetInfo"
)

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerClient interface {
	// Change runtime working mode
	ChangeMode(ctx context.Context, in *ChangeModeReq, opts ...grpc.CallOption) (*ChangeModeResp, error)
	// Execute runtime event
	ExecuteEvent(ctx context.Context, in *ExecuteEventReq, opts ...grpc.CallOption) (*ExecuteEventResp, error)
	// State stream request
	GetStateStream(ctx context.Context, in *RuntimeStateStreamReq, opts ...grpc.CallOption) (Worker_GetStateStreamClient, error)
	// System information
	GetSysInfo(ctx context.Context, in *SystemInfoReq, opts ...grpc.CallOption) (*SystemInfo, error)
	// Debug information about runtime daemon components ...
	GetInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*Info, error)
}

type workerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerClient(cc grpc.ClientConnInterface) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) ChangeMode(ctx context.Context, in *ChangeModeReq, opts ...grpc.CallOption) (*ChangeModeResp, error) {
	out := new(ChangeModeResp)
	err := c.cc.Invoke(ctx, Worker_ChangeMode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) ExecuteEvent(ctx context.Context, in *ExecuteEventReq, opts ...grpc.CallOption) (*ExecuteEventResp, error) {
	out := new(ExecuteEventResp)
	err := c.cc.Invoke(ctx, Worker_ExecuteEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) GetStateStream(ctx context.Context, in *RuntimeStateStreamReq, opts ...grpc.CallOption) (Worker_GetStateStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Worker_ServiceDesc.Streams[0], Worker_GetStateStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &workerGetStateStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Worker_GetStateStreamClient interface {
	Recv() (*RuntimeState, error)
	grpc.ClientStream
}

type workerGetStateStreamClient struct {
	grpc.ClientStream
}

func (x *workerGetStateStreamClient) Recv() (*RuntimeState, error) {
	m := new(RuntimeState)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workerClient) GetSysInfo(ctx context.Context, in *SystemInfoReq, opts ...grpc.CallOption) (*SystemInfo, error) {
	out := new(SystemInfo)
	err := c.cc.Invoke(ctx, Worker_GetSysInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerClient) GetInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*Info, error) {
	out := new(Info)
	err := c.cc.Invoke(ctx, Worker_GetInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServer is the server API for Worker service.
// All implementations must embed UnimplementedWorkerServer
// for forward compatibility
type WorkerServer interface {
	// Change runtime working mode
	ChangeMode(context.Context, *ChangeModeReq) (*ChangeModeResp, error)
	// Execute runtime event
	ExecuteEvent(context.Context, *ExecuteEventReq) (*ExecuteEventResp, error)
	// State stream request
	GetStateStream(*RuntimeStateStreamReq, Worker_GetStateStreamServer) error
	// System information
	GetSysInfo(context.Context, *SystemInfoReq) (*SystemInfo, error)
	// Debug information about runtime daemon components ...
	GetInfo(context.Context, *InfoReq) (*Info, error)
	mustEmbedUnimplementedWorkerServer()
}

// UnimplementedWorkerServer must be embedded to have forward compatible implementations.
type UnimplementedWorkerServer struct {
}

func (UnimplementedWorkerServer) ChangeMode(context.Context, *ChangeModeReq) (*ChangeModeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeMode not implemented")
}
func (UnimplementedWorkerServer) ExecuteEvent(context.Context, *ExecuteEventReq) (*ExecuteEventResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteEvent not implemented")
}
func (UnimplementedWorkerServer) GetStateStream(*RuntimeStateStreamReq, Worker_GetStateStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStateStream not implemented")
}
func (UnimplementedWorkerServer) GetSysInfo(context.Context, *SystemInfoReq) (*SystemInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSysInfo not implemented")
}
func (UnimplementedWorkerServer) GetInfo(context.Context, *InfoReq) (*Info, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedWorkerServer) mustEmbedUnimplementedWorkerServer() {}

// UnsafeWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServer will
// result in compilation errors.
type UnsafeWorkerServer interface {
	mustEmbedUnimplementedWorkerServer()
}

func RegisterWorkerServer(s grpc.ServiceRegistrar, srv WorkerServer) {
	s.RegisterService(&Worker_ServiceDesc, srv)
}

func _Worker_ChangeMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeModeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).ChangeMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_ChangeMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).ChangeMode(ctx, req.(*ChangeModeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_ExecuteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).ExecuteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_ExecuteEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).ExecuteEvent(ctx, req.(*ExecuteEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_GetStateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RuntimeStateStreamReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServer).GetStateStream(m, &workerGetStateStreamServer{stream})
}

type Worker_GetStateStreamServer interface {
	Send(*RuntimeState) error
	grpc.ServerStream
}

type workerGetStateStreamServer struct {
	grpc.ServerStream
}

func (x *workerGetStateStreamServer) Send(m *RuntimeState) error {
	return x.ServerStream.SendMsg(m)
}

func _Worker_GetSysInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).GetSysInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_GetSysInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).GetSysInfo(ctx, req.(*SystemInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Worker_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Worker_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServer).GetInfo(ctx, req.(*InfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Worker_ServiceDesc is the grpc.ServiceDesc for Worker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Worker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangeMode",
			Handler:    _Worker_ChangeMode_Handler,
		},
		{
			MethodName: "ExecuteEvent",
			Handler:    _Worker_ExecuteEvent_Handler,
		},
		{
			MethodName: "GetSysInfo",
			Handler:    _Worker_GetSysInfo_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _Worker_GetInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStateStream",
			Handler:       _Worker_GetStateStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "worker.proto",
}
